<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="Research methods for Psychology" />
<meta property="og:type" content="book" />


<meta property="og:description" content="A research methods for Psychology Textbook" />


<meta name="author" content="Matthew Crump" />

<meta name="date" content="2017-08-29" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A research methods for Psychology Textbook">

<title>Research methods for Psychology</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


<link rel="stylesheet" href="tufte.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#preamble"><span class="toc-section-number">1</span> preamble</a></li>
<li class="has-sub"><a href="2-psychological-science.html#psychological-science"><span class="toc-section-number">2</span> Psychological Science</a><ul>
<li class="has-sub"><a href="2-1-understanding-science.html#understanding-science"><span class="toc-section-number">2.1</span> Understanding Science</a><ul>
<li><a href="2-1-understanding-science.html#what-is-science"><span class="toc-section-number">2.1.1</span> What Is Science?</a></li>
<li><a href="2-1-understanding-science.html#features-of-science"><span class="toc-section-number">2.1.2</span> Features of Science</a></li>
<li><a href="2-1-understanding-science.html#science-versus-pseudoscience"><span class="toc-section-number">2.1.3</span> Science Versus Pseudoscience</a></li>
<li><a href="2-1-understanding-science.html#key-takeaways"><span class="toc-section-number">2.1.4</span> Key Takeaways</a></li>
<li><a href="2-1-understanding-science.html#exercises"><span class="toc-section-number">2.1.5</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="2-2-scientific-research-in-psychology.html#scientific-research-in-psychology"><span class="toc-section-number">2.2</span> Scientific Research in Psychology</a><ul>
<li><a href="2-2-scientific-research-in-psychology.html#a-model-of-scientific-research-in-psychology"><span class="toc-section-number">2.2.1</span> A Model of Scientific Research in Psychology</a></li>
<li><a href="2-2-scientific-research-in-psychology.html#who-conducts-scientific-research-in-psychology"><span class="toc-section-number">2.2.2</span> Who Conducts Scientific Research in Psychology?</a></li>
<li><a href="2-2-scientific-research-in-psychology.html#the-broader-purposes-of-scientific-research-in-psychology"><span class="toc-section-number">2.2.3</span> The Broader Purposes of Scientific Research in Psychology</a></li>
<li><a href="2-2-scientific-research-in-psychology.html#key-takeaways-1"><span class="toc-section-number">2.2.4</span> Key Takeaways</a></li>
<li><a href="2-2-scientific-research-in-psychology.html#exercises-1"><span class="toc-section-number">2.2.5</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="2-3-science-and-common-sense.html#science-and-common-sense"><span class="toc-section-number">2.3</span> Science and Common Sense</a><ul>
<li><a href="2-3-science-and-common-sense.html#can-we-rely-on-common-sense"><span class="toc-section-number">2.3.1</span> Can We Rely on Common Sense?</a></li>
<li><a href="2-3-science-and-common-sense.html#how-could-we-be-so-wrong"><span class="toc-section-number">2.3.2</span> How Could We Be So Wrong?</a></li>
<li><a href="2-3-science-and-common-sense.html#key-takeaways-2"><span class="toc-section-number">2.3.3</span> Key Takeaways</a></li>
<li><a href="2-3-science-and-common-sense.html#exercises-2"><span class="toc-section-number">2.3.4</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="2-4-science-and-clinical-practice.html#science-and-clinical-practice"><span class="toc-section-number">2.4</span> Science and Clinical Practice</a><ul>
<li><a href="2-4-science-and-clinical-practice.html#key-takeaways-3"><span class="toc-section-number">2.4.1</span> Key Takeaways</a></li>
<li><a href="2-4-science-and-clinical-practice.html#exercises-3"><span class="toc-section-number">2.4.2</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="2-5-using-psychological-science-to-inform-your-worldview.html#using-psychological-science-to-inform-your-worldview"><span class="toc-section-number">2.5</span> Using Psychological Science to Inform Your Worldview</a><ul>
<li><a href="2-5-using-psychological-science-to-inform-your-worldview.html#why-should-i-care-about-how-psychology-experiments-work"><span class="toc-section-number">2.5.1</span> Why Should I Care About How Psychology Experiments work?</a></li>
<li><a href="2-5-using-psychological-science-to-inform-your-worldview.html#evaluating-claims"><span class="toc-section-number">2.5.2</span> Evaluating Claims</a></li>
<li><a href="2-5-using-psychological-science-to-inform-your-worldview.html#testable-and-untestable-claims"><span class="toc-section-number">2.5.3</span> Testable and Untestable Claims</a></li>
<li><a href="2-5-using-psychological-science-to-inform-your-worldview.html#learning-how-not-to-be-crazy"><span class="toc-section-number">2.5.4</span> Learning How Not To Be Crazy</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="3-getting-started.html#getting-started"><span class="toc-section-number">3</span> Getting Started</a><ul>
<li class="has-sub"><a href="3-1-basic-concepts.html#basic-concepts"><span class="toc-section-number">3.1</span> Basic Concepts</a><ul>
<li><a href="3-1-basic-concepts.html#variables"><span class="toc-section-number">3.1.1</span> Variables</a></li>
<li><a href="3-1-basic-concepts.html#sampling-and-measurement"><span class="toc-section-number">3.1.2</span> Sampling and Measurement</a></li>
<li><a href="3-1-basic-concepts.html#statistical-relationships-between-variables"><span class="toc-section-number">3.1.3</span> Statistical Relationships Between Variables</a></li>
<li><a href="3-1-basic-concepts.html#differences-between-groups"><span class="toc-section-number">3.1.4</span> Differences Between Groups</a></li>
<li><a href="3-1-basic-concepts.html#correlations-between-quantitative-variables"><span class="toc-section-number">3.1.5</span> Correlations Between Quantitative Variables</a></li>
<li><a href="3-1-basic-concepts.html#correlation-does-not-imply-causation"><span class="toc-section-number">3.1.6</span> Correlation Does Not Imply Causation</a></li>
<li><a href="3-1-basic-concepts.html#lots-of-candy-could-lead-to-violence"><span class="toc-section-number">3.1.7</span> “Lots of Candy Could Lead to Violence”</a></li>
<li><a href="3-1-basic-concepts.html#key-takeaways-4"><span class="toc-section-number">3.1.8</span> Key Takeaways</a></li>
<li><a href="3-1-basic-concepts.html#exercises-4"><span class="toc-section-number">3.1.9</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="3-2-generating-good-research-questions.html#generating-good-research-questions"><span class="toc-section-number">3.2</span> Generating Good Research Questions</a><ul>
<li><a href="3-2-generating-good-research-questions.html#finding-inspiration"><span class="toc-section-number">3.2.1</span> Finding Inspiration</a></li>
<li><a href="3-2-generating-good-research-questions.html#generating-empirically-testable-research-questions"><span class="toc-section-number">3.2.2</span> Generating Empirically Testable Research Questions</a></li>
<li><a href="3-2-generating-good-research-questions.html#evaluating-research-questions"><span class="toc-section-number">3.2.3</span> Evaluating Research Questions</a></li>
<li><a href="3-2-generating-good-research-questions.html#interestingness"><span class="toc-section-number">3.2.4</span> Interestingness</a></li>
<li><a href="3-2-generating-good-research-questions.html#feasibility"><span class="toc-section-number">3.2.5</span> Feasibility</a></li>
<li><a href="3-2-generating-good-research-questions.html#key-takeaways-5"><span class="toc-section-number">3.2.6</span> Key takeaways</a></li>
<li><a href="3-2-generating-good-research-questions.html#exercises-5"><span class="toc-section-number">3.2.7</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-reviewing-the-research-literature.html#reviewing-the-research-literature"><span class="toc-section-number">3.3</span> Reviewing the Research Literature</a><ul>
<li><a href="3-3-reviewing-the-research-literature.html#what-is-the-research-literature"><span class="toc-section-number">3.3.1</span> What Is the Research Literature?</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#professional-journals"><span class="toc-section-number">3.3.2</span> Professional Journals</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#scholarly-books"><span class="toc-section-number">3.3.3</span> Scholarly Books</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#literature-search-strategies"><span class="toc-section-number">3.3.4</span> Literature Search Strategies</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#using-psycinfo-and-other-databases"><span class="toc-section-number">3.3.5</span> Using PsycINFO and Other Databases</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#using-other-search-techniques"><span class="toc-section-number">3.3.6</span> Using Other Search Techniques</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#google-scholar"><span class="toc-section-number">3.3.7</span> Google Scholar</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#what-to-search-for"><span class="toc-section-number">3.3.8</span> What to Search For</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#zotero-and-organizing-the-papers-you-find"><span class="toc-section-number">3.3.9</span> Zotero and Organizing the papers you find</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#key-takeaways-6"><span class="toc-section-number">3.3.10</span> Key Takeaways</a></li>
<li><a href="3-3-reviewing-the-research-literature.html#exercises-6"><span class="toc-section-number">3.3.11</span> Exercises</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="4-measurement.html#measurement"><span class="toc-section-number">4</span> Measurement</a><ul>
<li class="has-sub"><a href="4-1-understanding-psychological-measurement.html#understanding-psychological-measurement"><span class="toc-section-number">4.1</span> Understanding Psychological Measurement</a><ul>
<li><a href="4-1-understanding-psychological-measurement.html#what-is-measurement"><span class="toc-section-number">4.1.1</span> What Is Measurement?</a></li>
<li><a href="4-1-understanding-psychological-measurement.html#psychological-constructs"><span class="toc-section-number">4.1.2</span> Psychological Constructs</a></li>
<li><a href="4-1-understanding-psychological-measurement.html#operational-definitions"><span class="toc-section-number">4.1.3</span> Operational Definitions</a></li>
<li><a href="4-1-understanding-psychological-measurement.html#levels-of-measurement"><span class="toc-section-number">4.1.4</span> Levels of Measurement</a></li>
<li><a href="4-1-understanding-psychological-measurement.html#key-takeaways-7"><span class="toc-section-number">4.1.5</span> Key takeaways</a></li>
<li><a href="4-1-understanding-psychological-measurement.html#exercises-7"><span class="toc-section-number">4.1.6</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="4-2-reliability-and-validity-of-measurement.html#reliability-and-validity-of-measurement"><span class="toc-section-number">4.2</span> Reliability and Validity of Measurement</a><ul>
<li><a href="4-2-reliability-and-validity-of-measurement.html#reliability"><span class="toc-section-number">4.2.1</span> Reliability</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#test-retest-reliability"><span class="toc-section-number">4.2.2</span> Test-Retest Reliability</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#internal-consistency"><span class="toc-section-number">4.2.3</span> Internal Consistency</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#inter-rater-reliability"><span class="toc-section-number">4.2.4</span> Inter-rater Reliability</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#validity"><span class="toc-section-number">4.2.5</span> Validity</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#face-validity"><span class="toc-section-number">4.2.6</span> Face Validity</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#content-validity"><span class="toc-section-number">4.2.7</span> Content Validity</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#criterion-validity"><span class="toc-section-number">4.2.8</span> Criterion Validity</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#discriminant-validity"><span class="toc-section-number">4.2.9</span> Discriminant Validity</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#key-takeaways-8"><span class="toc-section-number">4.2.10</span> Key Takeaways</a></li>
<li><a href="4-2-reliability-and-validity-of-measurement.html#exercises-8"><span class="toc-section-number">4.2.11</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="4-3-practical-strategies-for-psychological-measurement.html#practical-strategies-for-psychological-measurement"><span class="toc-section-number">4.3</span> Practical Strategies for Psychological Measurement</a><ul>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#conceptually-defining-the-construct"><span class="toc-section-number">4.3.1</span> Conceptually Defining the Construct</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#deciding-on-an-operational-definition"><span class="toc-section-number">4.3.2</span> Deciding on an Operational Definition</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#using-an-existing-measure"><span class="toc-section-number">4.3.3</span> Using an Existing Measure</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#creating-your-own-measure"><span class="toc-section-number">4.3.4</span> Creating Your Own Measure</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#implementing-the-measure"><span class="toc-section-number">4.3.5</span> Implementing the Measure</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#evaluating-the-measure"><span class="toc-section-number">4.3.6</span> Evaluating the Measure</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#key-takeaways-9"><span class="toc-section-number">4.3.7</span> Key takeaways</a></li>
<li><a href="4-3-practical-strategies-for-psychological-measurement.html#exercises-9"><span class="toc-section-number">4.3.8</span> Exercises</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="5-single-factor-experiments.html#single-factor-experiments"><span class="toc-section-number">5</span> Single Factor Experiments</a><ul>
<li><a href="5-1-experiments-in-a-nutshell.html#experiments-in-a-nutshell"><span class="toc-section-number">5.1</span> Experiments in a nutshell</a></li>
<li><a href="5-2-an-example-psychology-experiment.html#an-example-psychology-experiment"><span class="toc-section-number">5.2</span> An example Psychology Experiment</a></li>
<li class="has-sub"><a href="5-3-more-experimental-basics.html#more-experimental-basics"><span class="toc-section-number">5.3</span> More Experimental Basics</a><ul>
<li><a href="5-3-more-experimental-basics.html#what-is-an-experiment"><span class="toc-section-number">5.3.1</span> What Is an Experiment?</a></li>
<li><a href="5-3-more-experimental-basics.html#four-big-validities"><span class="toc-section-number">5.3.2</span> Four Big Validities</a></li>
<li><a href="5-3-more-experimental-basics.html#internal-validity"><span class="toc-section-number">5.3.3</span> Internal Validity</a></li>
<li><a href="5-3-more-experimental-basics.html#external-validity"><span class="toc-section-number">5.3.4</span> External Validity</a></li>
<li><a href="5-3-more-experimental-basics.html#construct-validity"><span class="toc-section-number">5.3.5</span> Construct Validity</a></li>
<li><a href="5-3-more-experimental-basics.html#statistical-validity"><span class="toc-section-number">5.3.6</span> Statistical Validity</a></li>
<li><a href="5-3-more-experimental-basics.html#prioritizing-validities"><span class="toc-section-number">5.3.7</span> Prioritizing Validities</a></li>
<li><a href="5-3-more-experimental-basics.html#manipulation-of-the-independent-variable"><span class="toc-section-number">5.3.8</span> Manipulation of the Independent Variable</a></li>
<li><a href="5-3-more-experimental-basics.html#control-of-extraneous-variables"><span class="toc-section-number">5.3.9</span> Control of Extraneous Variables</a></li>
<li><a href="5-3-more-experimental-basics.html#extraneous-variables-as-noise"><span class="toc-section-number">5.3.10</span> Extraneous Variables as “Noise”</a></li>
<li><a href="5-3-more-experimental-basics.html#extraneous-variables-as-confounding-variables"><span class="toc-section-number">5.3.11</span> Extraneous Variables as Confounding Variables</a></li>
<li><a href="5-3-more-experimental-basics.html#section"><span class="toc-section-number">5.3.12</span> </a></li>
<li><a href="5-3-more-experimental-basics.html#section-1"><span class="toc-section-number">5.3.13</span> </a></li>
</ul></li>
<li class="has-sub"><a href="5-4-experimental-design.html#experimental-design"><span class="toc-section-number">5.4</span> Experimental Design</a><ul>
<li><a href="5-4-experimental-design.html#between-subjects-experiments"><span class="toc-section-number">5.4.1</span> Between-Subjects Experiments</a></li>
<li><a href="5-4-experimental-design.html#random-assignment"><span class="toc-section-number">5.4.2</span> Random Assignment</a></li>
<li><a href="5-4-experimental-design.html#treatment-and-control-conditions"><span class="toc-section-number">5.4.3</span> Treatment and Control Conditions</a></li>
<li><a href="5-4-experimental-design.html#within-subjects-experiments"><span class="toc-section-number">5.4.4</span> Within-Subjects Experiments</a></li>
<li><a href="5-4-experimental-design.html#carryover-effects-and-counterbalancing"><span class="toc-section-number">5.4.5</span> Carryover Effects and Counterbalancing</a></li>
<li><a href="5-4-experimental-design.html#simultaneous-within-subjects-designs"><span class="toc-section-number">5.4.6</span> Simultaneous Within-Subjects Designs</a></li>
<li><a href="5-4-experimental-design.html#between-subjects-or-within-subjects"><span class="toc-section-number">5.4.7</span> Between-Subjects or Within-Subjects?</a></li>
<li><a href="5-4-experimental-design.html#section-2"><span class="toc-section-number">5.4.8</span> </a></li>
<li><a href="5-4-experimental-design.html#section-3"><span class="toc-section-number">5.4.9</span> </a></li>
</ul></li>
<li class="has-sub"><a href="5-5-conducting-experiments.html#conducting-experiments"><span class="toc-section-number">5.5</span> Conducting Experiments</a><ul>
<li><a href="5-5-conducting-experiments.html#recruiting-participants"><span class="toc-section-number">5.5.1</span> Recruiting Participants</a></li>
<li><a href="5-5-conducting-experiments.html#standardizing-the-procedure"><span class="toc-section-number">5.5.2</span> Standardizing the Procedure</a></li>
<li><a href="5-5-conducting-experiments.html#record-keeping"><span class="toc-section-number">5.5.3</span> Record Keeping</a></li>
<li><a href="5-5-conducting-experiments.html#pilot-testing"><span class="toc-section-number">5.5.4</span> Pilot Testing</a></li>
<li><a href="5-5-conducting-experiments.html#section-4"><span class="toc-section-number">5.5.5</span> </a></li>
<li><a href="5-5-conducting-experiments.html#section-5"><span class="toc-section-number">5.5.6</span> </a></li>
</ul></li>
<li class="has-sub"><a href="5-6-single-factor-designs-with-2-levels.html#single-factor-designs-with-2-levels"><span class="toc-section-number">5.6</span> Single Factor Designs with 2 levels</a><ul>
<li><a href="5-6-single-factor-designs-with-2-levels.html#the-basic-empirical-question-is-there-a-difference"><span class="toc-section-number">5.6.1</span> The basic empirical question: Is there a difference?</a></li>
<li><a href="5-6-single-factor-designs-with-2-levels.html#chance-and-change"><span class="toc-section-number">5.6.2</span> Chance and Change</a></li>
<li><a href="5-6-single-factor-designs-with-2-levels.html#distributions"><span class="toc-section-number">5.6.3</span> Distributions</a></li>
<li><a href="5-6-single-factor-designs-with-2-levels.html#differences-can-arise-by-chance-because-of-sampling"><span class="toc-section-number">5.6.4</span> Differences can arise by chance because of sampling</a></li>
<li><a href="5-6-single-factor-designs-with-2-levels.html#what-kind-of-differences-can-chance-produce"><span class="toc-section-number">5.6.5</span> What kind of differences can chance produce?</a></li>
<li><a href="5-6-single-factor-designs-with-2-levels.html#chance-can-produce-differences-between-conditions-in-an-experiment"><span class="toc-section-number">5.6.6</span> Chance can produce differences between conditions in an experiment</a></li>
</ul></li>
<li class="has-sub"><a href="5-7-level-designs-and-t-tests.html#level-designs-and-t-tests"><span class="toc-section-number">5.7</span> 2 level designs and t-tests</a><ul>
<li><a href="5-7-level-designs-and-t-tests.html#an-example"><span class="toc-section-number">5.7.1</span> An example</a></li>
<li><a href="5-7-level-designs-and-t-tests.html#simulating-the-null"><span class="toc-section-number">5.7.2</span> Simulating the null</a></li>
<li><a href="5-7-level-designs-and-t-tests.html#simulating-real-differences"><span class="toc-section-number">5.7.3</span> Simulating real differences</a></li>
</ul></li>
<li class="has-sub"><a href="5-8-single-factor-designs-with-multiple-levels.html#single-factor-designs-with-multiple-levels"><span class="toc-section-number">5.8</span> Single Factor Designs with multiple levels</a><ul>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#quantitative-vs.qualitative-independent-variables"><span class="toc-section-number">5.8.1</span> Quantitative vs. Qualitative Independent variables</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#interpreting-the-pattern-of-results"><span class="toc-section-number">5.8.2</span> Interpreting the pattern of results</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#an-example-one-way-anova-using-r"><span class="toc-section-number">5.8.3</span> An example one-way ANOVA using R</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#looking-at-the-means"><span class="toc-section-number">5.8.4</span> Looking at the means</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#plotting-the-data"><span class="toc-section-number">5.8.5</span> Plotting the data</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#conducting-the-anova"><span class="toc-section-number">5.8.6</span> Conducting the ANOVA</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#comparisons-between-conditions"><span class="toc-section-number">5.8.7</span> Comparisons between conditions</a></li>
<li><a href="5-8-single-factor-designs-with-multiple-levels.html#writing-it-all-up"><span class="toc-section-number">5.8.8</span> Writing it all up</a></li>
</ul></li>
</ul></li>
<li><a href="6-final-words.html#final-words"><span class="toc-section-number">6</span> Final Words</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="level-designs-and-t-tests" class="section level2">
<h2><span class="header-section-number">5.7</span> 2 level designs and t-tests</h2>
<p>There are multiple ways to estimate whether chance is responsible for a difference in an experiment. By far the most common approach is to use a t-test. The t-test is a statitiscal method for analyzing the data in two conditions to determine the likelihood that any observed difference could have been produced by chance. You can refer to the inferential statistics chapter, your old notes from statistics, discussions of t-tests in the lab manual, and google t-tests to learn more about how they work. For now, we will briefly describe the three different kinds of t-tests, and give an example of how they are used to analyze data, and how the results from a t-test are reported in journal article.</p>
<p>The three most common versions of the t-test are: one-sample t-test, independent samples t-test, and the paired samples t-test. The one sample t-test is used to test whether a sample mean could have come from a particular population. The independent samples t-test is used in between-subjects designs, to test whether the sample mean in one condition is different from the sample mean in another condition. The paired samples t-test is used in within-subjects designs, to test whether the sample mean in one condition is different from the sample mean in the other condition.</p>
<p>All t-tests give the same basic information, a t-value, and a p-value. Simply, the p-value gives the probability that the observed difference between means could have been produced by chance alone. If we dive into the details, we will see that the p-value estimate depends on several assumptions being met, and also has more nuanced meanings. But for now, it gives us what we want, an estimate of the likelihood that chance could have produced the difference we observed. When the p-value is very small (e.g., less than .05, or 5%), many researchers would conclude that a difference “statistically significant”, and probably not produced by chance.</p>
<div id="an-example" class="section level3">
<h3><span class="header-section-number">5.7.1</span> An example</h3>
<div class="figure"><span id="fig:unnamed-chunk-7"></span>
<p class="caption marginnote shownote">
Figure 5.2: Sample test scores for both groups were randomly drawn from this distribution, with mean 75, and standard deviation 5.
</p>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-7-1.png" alt="Sample test scores for both groups were randomly drawn from this distribution, with mean 75, and standard deviation 5." width="672"  />
</div>
<p>Imagine a between-subjects experiment on 20 students (10 in each group), asking whether wearing a red shirt or a blue shirt changes test performance on a midterm. The IV is shirt color (red vs. blue), and the DV is test performance (percentage on the midterm). We have no good reason to think that shirt color will change test performance, so we expect that the red and blue shirt groups will have similar averages. We can simulate this experiment by randomly sampling scores for both groups from the same underlying distribution (see the figure).</p>
<p>Below are some imaginary results from the experiment.</p>
<table>
<thead>
<tr class="header">
<th align="right">blue</th>
<th align="right">red</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">77</td>
<td align="right">78</td>
</tr>
<tr class="even">
<td align="right">74</td>
<td align="right">65</td>
</tr>
<tr class="odd">
<td align="right">78</td>
<td align="right">78</td>
</tr>
<tr class="even">
<td align="right">69</td>
<td align="right">73</td>
</tr>
<tr class="odd">
<td align="right">77</td>
<td align="right">76</td>
</tr>
<tr class="even">
<td align="right">68</td>
<td align="right">75</td>
</tr>
<tr class="odd">
<td align="right">72</td>
<td align="right">72</td>
</tr>
<tr class="even">
<td align="right">79</td>
<td align="right">69</td>
</tr>
<tr class="odd">
<td align="right">76</td>
<td align="right">79</td>
</tr>
<tr class="even">
<td align="right">72</td>
<td align="right">58</td>
</tr>
</tbody>
</table>
<p>Looking at the individual scores is informative, but doesn’t immediately give us a sense of the difference between groups. So, we can compute the group means:</p>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="right">scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Blue</td>
<td align="right">74.2</td>
</tr>
<tr class="even">
<td align="left">Red</td>
<td align="right">72.3</td>
</tr>
</tbody>
</table>
<p>The means are not exactly the same, so we might want to conclude that the studying manipulation influences test performance (after all, it probably does in the real world). However, the simulated data for both groups was actually sampled from the same distribution, with mean 75, and standard deviation 5. As a result, we know that the difference we observed between the sample means was due to random chance. We know this only because I simulated the data. If this was real data, then we wouldn’t know if the two sample means came from the the same distribution or different distributions.</p>
<p>Even though we know the difference in this example was caused by random sampling, we can still compute a t-test on the simulated data.The following t-test was conducted using R.</p>
<pre><code>## 
##  Two Sample t-test
## 
## data:  blue and red
## t = 0.7817, df = 18, p-value = 0.4446
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.206484  7.006484
## sample estimates:
## mean of x mean of y 
##      74.2      72.3</code></pre>
<p>If this was a real experiment that was published in a manuscript, then we would want to report the results by: 1) reporting the means in each condition, and 2) reporting the t-test, including the t-value, the degrees of freedom, and the associated p-value. The write-up might look something like this:</p>
<p>Mean test performance in the red shirt group (72.3) was not significantly different from mean test performance in the blue shirt group (74.2), t(18) = 0.782, p = 0.445.</p>
</div>
<div id="simulating-the-null" class="section level3">
<h3><span class="header-section-number">5.7.2</span> Simulating the null</h3>
<p>In the above example we found a small difference between the means of the red and blue shirt groups. We know this difference was produced by random sampling, and the t-test also returned a large p-value, indicating that chance could produce this small difference fairly often. This is all very sensible, as we don’t have a good reason to think that wearing different colored shirts should impact test performance.</p>
<p>However, as previously discussed, just the act of measuring test performance and splitting people into two groups can produce differences between the sample means. Importantly, even when there are no true differences, analyzing the data with a t-test will sometimes produce small p-values (e.g., &lt; .05). For example, when there are no true differences, but there is variability in the measure, then approximately five percent of the time the t-test will return a p &lt; .05. In other words, if we conducted the t-shirt experiment 100 times, we would expect that 5 of those experiments would produce a difference between the red and blue shirts, that a t-test would claim is unlikely to be produced by chance.</p>
<p>We can get a sense of this by repeating the above experiment 1000s of times. Each time we will take new random samples of test scores for the red and blue shirt groups, then we will compute the sample mean for each group, and then find the difference between the red and blue shirt groups. We can save the difference that we find for every replication, and then plot a histogram of the differences. This will show us the kind of differences that can be produced in this experiment by chance alone.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-12-1.png" width="672"  /></p>
<p>The first histogram shows the range of differences that can occur by chance alone. The distribution is centered on 0, because on average there should be no differences between these two sample means (after all they come from the same parent distribution). We also see the range extends to around -5% to +5%. This shows that some replications have the red shirt group have up to a 5% higher test score than the blue shirt group, or vice versa.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-13-1.png" width="672"  /></p>
<p>For each replication, the resulting t-value and p-value was recorded. The second histogram shows the distribution of t-values, and the third histogram shows the distribution of p-values.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-14-1.png" width="672"  /></p>
<p>The distribution of p-values is flat, meaning that any p-value between 0 and 100 should occur with the same frequency. This shows that, just by random sampling alone, we should expect to find significant differences (p&lt;.05), about 5% of the time.</p>
</div>
<div id="simulating-real-differences" class="section level3">
<h3><span class="header-section-number">5.7.3</span> Simulating real differences</h3>
<p>Imagine a between-subjects experiment on 20 students (10 in each group), asking whether studying or not changes test performance on a midterm. The IV is studying (studying vs. not studying), and the DV is test performance (percentage on the midterm). We assume that studying is important for passing a test, so the group who studies should have higher test scores than the group who doesn’t. We can simulate this experiment by randomly sampling scores for the study group from a distribution with a higher mean than the no study group.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-15-1.png" width="672"  /></p>
<p>For example, the histograms on the right show that the sample scores in the study group will come from a distribution with mean = 80, and standard deviation = 5; and the sample scores in the no study group will come from a distribution with mean = 65, and standard deviation 5. The simulated scores in the experiment are in the table below:</p>
<table>
<thead>
<tr class="header">
<th align="right">study</th>
<th align="right">no_study</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">74</td>
<td align="right">63</td>
</tr>
<tr class="even">
<td align="right">79</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="right">83</td>
<td align="right">70</td>
</tr>
<tr class="even">
<td align="right">83</td>
<td align="right">70</td>
</tr>
<tr class="odd">
<td align="right">79</td>
<td align="right">62</td>
</tr>
<tr class="even">
<td align="right">75</td>
<td align="right">77</td>
</tr>
<tr class="odd">
<td align="right">81</td>
<td align="right">60</td>
</tr>
<tr class="even">
<td align="right">81</td>
<td align="right">65</td>
</tr>
<tr class="odd">
<td align="right">80</td>
<td align="right">67</td>
</tr>
<tr class="even">
<td align="right">84</td>
<td align="right">70</td>
</tr>
</tbody>
</table>
<p>The group means are:</p>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="right">scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no_study</td>
<td align="right">66.5</td>
</tr>
<tr class="even">
<td align="left">study</td>
<td align="right">79.9</td>
</tr>
</tbody>
</table>
<p>And, the t-test is:</p>
<pre><code>## 
##  Two Sample t-test
## 
## data:  study and no_study
## t = 6.7623, df = 18, p-value = 2.458e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   9.236851 17.563149
## sample estimates:
## mean of x mean of y 
##      79.9      66.5</code></pre>
<p>The results of the t-test could be reported as follows:</p>
<p>Mean test performance in the study group group (79.9) was significantly higher than mean test performance in the no study group (66.5), t(18) = 6.762, p = 0.</p>
<p>Or, more simply: Students who studied (79.9) had higher averages than students who didn’t study (66.5), t(18) = 6.762, p = 0.</p>
</div>
</div>
<p style="text-align: center;">
<a href="5-6-single-factor-designs-with-2-levels.html"><button class="btn btn-default">Previous</button></a>
<a href="5-8-single-factor-designs-with-multiple-levels.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>



</body>
</html>
