<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Research methods for Psychology</title>
  <meta name="description" content="A research methods for Psychology Textbook">
  <meta name="generator" content="bookdown 0.4.1 and GitBook 2.6.7">

  <meta property="og:title" content="Research methods for Psychology" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A research methods for Psychology Textbook" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Research methods for Psychology" />
  
  <meta name="twitter:description" content="A research methods for Psychology Textbook" />
  

<meta name="author" content="Matthew Crump">


<meta name="date" content="2017-08-07">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="simulating-the-null.html">
<link rel="next" href="final-words.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Research Methods</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="psychological-science.html"><a href="psychological-science.html"><i class="fa fa-check"></i><b>1</b> Psychological Science</a><ul>
<li class="chapter" data-level="1.1" data-path="psychological-science.html"><a href="psychological-science.html#understanding-science"><i class="fa fa-check"></i><b>1.1</b> Understanding Science</a><ul>
<li class="chapter" data-level="1.1.1" data-path="psychological-science.html"><a href="psychological-science.html#what-is-science"><i class="fa fa-check"></i><b>1.1.1</b> What Is Science?</a></li>
<li class="chapter" data-level="1.1.2" data-path="psychological-science.html"><a href="psychological-science.html#features-of-science"><i class="fa fa-check"></i><b>1.1.2</b> Features of Science</a></li>
<li class="chapter" data-level="1.1.3" data-path="psychological-science.html"><a href="psychological-science.html#science-versus-pseudoscience"><i class="fa fa-check"></i><b>1.1.3</b> Science Versus Pseudoscience</a></li>
<li class="chapter" data-level="1.1.4" data-path="psychological-science.html"><a href="psychological-science.html#key-takeaways"><i class="fa fa-check"></i><b>1.1.4</b> Key Takeaways</a></li>
<li class="chapter" data-level="1.1.5" data-path="psychological-science.html"><a href="psychological-science.html#exercises"><i class="fa fa-check"></i><b>1.1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="psychological-science.html"><a href="psychological-science.html#scientific-research-in-psychology"><i class="fa fa-check"></i><b>1.2</b> Scientific Research in Psychology</a><ul>
<li class="chapter" data-level="1.2.1" data-path="psychological-science.html"><a href="psychological-science.html#a-model-of-scientific-research-in-psychology"><i class="fa fa-check"></i><b>1.2.1</b> A Model of Scientific Research in Psychology</a></li>
<li class="chapter" data-level="1.2.2" data-path="psychological-science.html"><a href="psychological-science.html#who-conducts-scientific-research-in-psychology"><i class="fa fa-check"></i><b>1.2.2</b> Who Conducts Scientific Research in Psychology?</a></li>
<li class="chapter" data-level="1.2.3" data-path="psychological-science.html"><a href="psychological-science.html#the-broader-purposes-of-scientific-research-in-psychology"><i class="fa fa-check"></i><b>1.2.3</b> The Broader Purposes of Scientific Research in Psychology</a></li>
<li class="chapter" data-level="1.2.4" data-path="psychological-science.html"><a href="psychological-science.html#key-takeaways-1"><i class="fa fa-check"></i><b>1.2.4</b> Key Takeaways</a></li>
<li class="chapter" data-level="1.2.5" data-path="psychological-science.html"><a href="psychological-science.html#exercises-1"><i class="fa fa-check"></i><b>1.2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="psychological-science.html"><a href="psychological-science.html#science-and-common-sense"><i class="fa fa-check"></i><b>1.3</b> Science and Common Sense</a><ul>
<li class="chapter" data-level="1.3.1" data-path="psychological-science.html"><a href="psychological-science.html#can-we-rely-on-common-sense"><i class="fa fa-check"></i><b>1.3.1</b> Can We Rely on Common Sense?</a></li>
<li class="chapter" data-level="1.3.2" data-path="psychological-science.html"><a href="psychological-science.html#how-could-we-be-so-wrong"><i class="fa fa-check"></i><b>1.3.2</b> How Could We Be So Wrong?</a></li>
<li class="chapter" data-level="1.3.3" data-path="psychological-science.html"><a href="psychological-science.html#key-takeaways-2"><i class="fa fa-check"></i><b>1.3.3</b> Key Takeaways</a></li>
<li class="chapter" data-level="1.3.4" data-path="psychological-science.html"><a href="psychological-science.html#exercises-2"><i class="fa fa-check"></i><b>1.3.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="psychological-science.html"><a href="psychological-science.html#science-and-clinical-practice"><i class="fa fa-check"></i><b>1.4</b> Science and Clinical Practice</a><ul>
<li class="chapter" data-level="1.4.1" data-path="psychological-science.html"><a href="psychological-science.html#key-takeaways-3"><i class="fa fa-check"></i><b>1.4.1</b> Key Takeaways</a></li>
<li class="chapter" data-level="1.4.2" data-path="psychological-science.html"><a href="psychological-science.html#exercises-3"><i class="fa fa-check"></i><b>1.4.2</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="psychological-science.html"><a href="psychological-science.html#using-psychological-science-to-inform-your-worldview"><i class="fa fa-check"></i><b>1.5</b> Using Psychological Science to Inform Your Worldview</a><ul>
<li class="chapter" data-level="1.5.1" data-path="psychological-science.html"><a href="psychological-science.html#why-should-i-care-about-how-psychology-experiments-work"><i class="fa fa-check"></i><b>1.5.1</b> Why Should I Care About How Psychology Experiments work?</a></li>
<li class="chapter" data-level="1.5.2" data-path="psychological-science.html"><a href="psychological-science.html#evaluating-claims"><i class="fa fa-check"></i><b>1.5.2</b> Evaluating Claims</a></li>
<li class="chapter" data-level="1.5.3" data-path="psychological-science.html"><a href="psychological-science.html#testable-and-untestable-claims"><i class="fa fa-check"></i><b>1.5.3</b> Testable and Untestable Claims</a></li>
<li class="chapter" data-level="1.5.4" data-path="psychological-science.html"><a href="psychological-science.html#learning-how-not-to-be-crazy"><i class="fa fa-check"></i><b>1.5.4</b> Learning How Not To Be Crazy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>2</b> Getting Started</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-started.html"><a href="getting-started.html#basic-concepts"><i class="fa fa-check"></i><b>2.1</b> Basic Concepts</a><ul>
<li class="chapter" data-level="2.1.1" data-path="getting-started.html"><a href="getting-started.html#variables"><i class="fa fa-check"></i><b>2.1.1</b> Variables</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-started.html"><a href="getting-started.html#sampling-and-measurement"><i class="fa fa-check"></i><b>2.1.2</b> Sampling and Measurement</a></li>
<li class="chapter" data-level="2.1.3" data-path="getting-started.html"><a href="getting-started.html#statistical-relationships-between-variables"><i class="fa fa-check"></i><b>2.1.3</b> Statistical Relationships Between Variables</a></li>
<li class="chapter" data-level="2.1.4" data-path="getting-started.html"><a href="getting-started.html#differences-between-groups"><i class="fa fa-check"></i><b>2.1.4</b> Differences Between Groups</a></li>
<li class="chapter" data-level="2.1.5" data-path="getting-started.html"><a href="getting-started.html#correlations-between-quantitative-variables"><i class="fa fa-check"></i><b>2.1.5</b> Correlations Between Quantitative Variables</a></li>
<li class="chapter" data-level="2.1.6" data-path="getting-started.html"><a href="getting-started.html#correlation-does-not-imply-causation"><i class="fa fa-check"></i><b>2.1.6</b> Correlation Does Not Imply Causation</a></li>
<li class="chapter" data-level="2.1.7" data-path="getting-started.html"><a href="getting-started.html#lots-of-candy-could-lead-to-violence"><i class="fa fa-check"></i><b>2.1.7</b> “Lots of Candy Could Lead to Violence”</a></li>
<li class="chapter" data-level="2.1.8" data-path="getting-started.html"><a href="getting-started.html#key-takeaways-4"><i class="fa fa-check"></i><b>2.1.8</b> Key Takeaways</a></li>
<li class="chapter" data-level="2.1.9" data-path="getting-started.html"><a href="getting-started.html#exercises-4"><i class="fa fa-check"></i><b>2.1.9</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-started.html"><a href="getting-started.html#generating-good-research-questions"><i class="fa fa-check"></i><b>2.2</b> Generating Good Research Questions</a><ul>
<li class="chapter" data-level="2.2.1" data-path="getting-started.html"><a href="getting-started.html#finding-inspiration"><i class="fa fa-check"></i><b>2.2.1</b> Finding Inspiration</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-started.html"><a href="getting-started.html#generating-empirically-testable-research-questions"><i class="fa fa-check"></i><b>2.2.2</b> Generating Empirically Testable Research Questions</a></li>
<li class="chapter" data-level="2.2.3" data-path="getting-started.html"><a href="getting-started.html#evaluating-research-questions"><i class="fa fa-check"></i><b>2.2.3</b> Evaluating Research Questions</a></li>
<li class="chapter" data-level="2.2.4" data-path="getting-started.html"><a href="getting-started.html#interestingness"><i class="fa fa-check"></i><b>2.2.4</b> Interestingness</a></li>
<li class="chapter" data-level="2.2.5" data-path="getting-started.html"><a href="getting-started.html#feasibility"><i class="fa fa-check"></i><b>2.2.5</b> Feasibility</a></li>
<li class="chapter" data-level="2.2.6" data-path="getting-started.html"><a href="getting-started.html#key-takeaways-5"><i class="fa fa-check"></i><b>2.2.6</b> Key takeaways</a></li>
<li class="chapter" data-level="2.2.7" data-path="getting-started.html"><a href="getting-started.html#exercises-5"><i class="fa fa-check"></i><b>2.2.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-started.html"><a href="getting-started.html#reviewing-the-research-literature"><i class="fa fa-check"></i><b>2.3</b> Reviewing the Research Literature</a><ul>
<li class="chapter" data-level="2.3.1" data-path="getting-started.html"><a href="getting-started.html#what-is-the-research-literature"><i class="fa fa-check"></i><b>2.3.1</b> What Is the Research Literature?</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-started.html"><a href="getting-started.html#professional-journals"><i class="fa fa-check"></i><b>2.3.2</b> Professional Journals</a></li>
<li class="chapter" data-level="2.3.3" data-path="getting-started.html"><a href="getting-started.html#scholarly-books"><i class="fa fa-check"></i><b>2.3.3</b> Scholarly Books</a></li>
<li class="chapter" data-level="2.3.4" data-path="getting-started.html"><a href="getting-started.html#literature-search-strategies"><i class="fa fa-check"></i><b>2.3.4</b> Literature Search Strategies</a></li>
<li class="chapter" data-level="2.3.5" data-path="getting-started.html"><a href="getting-started.html#using-psycinfo-and-other-databases"><i class="fa fa-check"></i><b>2.3.5</b> Using PsycINFO and Other Databases</a></li>
<li class="chapter" data-level="2.3.6" data-path="getting-started.html"><a href="getting-started.html#using-other-search-techniques"><i class="fa fa-check"></i><b>2.3.6</b> Using Other Search Techniques</a></li>
<li class="chapter" data-level="2.3.7" data-path="getting-started.html"><a href="getting-started.html#google-scholar"><i class="fa fa-check"></i><b>2.3.7</b> Google Scholar</a></li>
<li class="chapter" data-level="2.3.8" data-path="getting-started.html"><a href="getting-started.html#what-to-search-for"><i class="fa fa-check"></i><b>2.3.8</b> What to Search For</a></li>
<li class="chapter" data-level="2.3.9" data-path="getting-started.html"><a href="getting-started.html#zotero-and-organizing-the-papers-you-find"><i class="fa fa-check"></i><b>2.3.9</b> Zotero and Organizing the papers you find</a></li>
<li class="chapter" data-level="2.3.10" data-path="getting-started.html"><a href="getting-started.html#key-takeaways-6"><i class="fa fa-check"></i><b>2.3.10</b> Key Takeaways</a></li>
<li class="chapter" data-level="2.3.11" data-path="getting-started.html"><a href="getting-started.html#exercises-6"><i class="fa fa-check"></i><b>2.3.11</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="measurement.html"><a href="measurement.html"><i class="fa fa-check"></i><b>3</b> Measurement</a><ul>
<li class="chapter" data-level="3.1" data-path="measurement.html"><a href="measurement.html#understanding-psychological-measurement"><i class="fa fa-check"></i><b>3.1</b> Understanding Psychological Measurement</a><ul>
<li class="chapter" data-level="3.1.1" data-path="measurement.html"><a href="measurement.html#what-is-measurement"><i class="fa fa-check"></i><b>3.1.1</b> What Is Measurement?</a></li>
<li class="chapter" data-level="3.1.2" data-path="measurement.html"><a href="measurement.html#psychological-constructs"><i class="fa fa-check"></i><b>3.1.2</b> Psychological Constructs</a></li>
<li class="chapter" data-level="3.1.3" data-path="measurement.html"><a href="measurement.html#operational-definitions"><i class="fa fa-check"></i><b>3.1.3</b> Operational Definitions</a></li>
<li class="chapter" data-level="3.1.4" data-path="measurement.html"><a href="measurement.html#levels-of-measurement"><i class="fa fa-check"></i><b>3.1.4</b> Levels of Measurement</a></li>
<li class="chapter" data-level="3.1.5" data-path="measurement.html"><a href="measurement.html#key-takeaways-7"><i class="fa fa-check"></i><b>3.1.5</b> Key takeaways</a></li>
<li class="chapter" data-level="3.1.6" data-path="measurement.html"><a href="measurement.html#exercises-7"><i class="fa fa-check"></i><b>3.1.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="measurement.html"><a href="measurement.html#reliability-and-validity-of-measurement"><i class="fa fa-check"></i><b>3.2</b> Reliability and Validity of Measurement</a><ul>
<li class="chapter" data-level="3.2.1" data-path="measurement.html"><a href="measurement.html#reliability"><i class="fa fa-check"></i><b>3.2.1</b> Reliability</a></li>
<li class="chapter" data-level="3.2.2" data-path="measurement.html"><a href="measurement.html#test-retest-reliability"><i class="fa fa-check"></i><b>3.2.2</b> Test-Retest Reliability</a></li>
<li class="chapter" data-level="3.2.3" data-path="measurement.html"><a href="measurement.html#internal-consistency"><i class="fa fa-check"></i><b>3.2.3</b> Internal Consistency</a></li>
<li class="chapter" data-level="3.2.4" data-path="measurement.html"><a href="measurement.html#inter-rater-reliability"><i class="fa fa-check"></i><b>3.2.4</b> Inter-rater Reliability</a></li>
<li class="chapter" data-level="3.2.5" data-path="measurement.html"><a href="measurement.html#validity"><i class="fa fa-check"></i><b>3.2.5</b> Validity</a></li>
<li class="chapter" data-level="3.2.6" data-path="measurement.html"><a href="measurement.html#face-validity"><i class="fa fa-check"></i><b>3.2.6</b> Face Validity</a></li>
<li class="chapter" data-level="3.2.7" data-path="measurement.html"><a href="measurement.html#content-validity"><i class="fa fa-check"></i><b>3.2.7</b> Content Validity</a></li>
<li class="chapter" data-level="3.2.8" data-path="measurement.html"><a href="measurement.html#criterion-validity"><i class="fa fa-check"></i><b>3.2.8</b> Criterion Validity</a></li>
<li class="chapter" data-level="3.2.9" data-path="measurement.html"><a href="measurement.html#discriminant-validity"><i class="fa fa-check"></i><b>3.2.9</b> Discriminant Validity</a></li>
<li class="chapter" data-level="3.2.10" data-path="measurement.html"><a href="measurement.html#key-takeaways-8"><i class="fa fa-check"></i><b>3.2.10</b> Key Takeaways</a></li>
<li class="chapter" data-level="3.2.11" data-path="measurement.html"><a href="measurement.html#exercises-8"><i class="fa fa-check"></i><b>3.2.11</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="measurement.html"><a href="measurement.html#practical-strategies-for-psychological-measurement"><i class="fa fa-check"></i><b>3.3</b> Practical Strategies for Psychological Measurement</a><ul>
<li class="chapter" data-level="3.3.1" data-path="measurement.html"><a href="measurement.html#conceptually-defining-the-construct"><i class="fa fa-check"></i><b>3.3.1</b> Conceptually Defining the Construct</a></li>
<li class="chapter" data-level="3.3.2" data-path="measurement.html"><a href="measurement.html#deciding-on-an-operational-definition"><i class="fa fa-check"></i><b>3.3.2</b> Deciding on an Operational Definition</a></li>
<li class="chapter" data-level="3.3.3" data-path="measurement.html"><a href="measurement.html#using-an-existing-measure"><i class="fa fa-check"></i><b>3.3.3</b> Using an Existing Measure</a></li>
<li class="chapter" data-level="3.3.4" data-path="measurement.html"><a href="measurement.html#creating-your-own-measure"><i class="fa fa-check"></i><b>3.3.4</b> Creating Your Own Measure</a></li>
<li class="chapter" data-level="3.3.5" data-path="measurement.html"><a href="measurement.html#implementing-the-measure"><i class="fa fa-check"></i><b>3.3.5</b> Implementing the Measure</a></li>
<li class="chapter" data-level="3.3.6" data-path="measurement.html"><a href="measurement.html#evaluating-the-measure"><i class="fa fa-check"></i><b>3.3.6</b> Evaluating the Measure</a></li>
<li class="chapter" data-level="3.3.7" data-path="measurement.html"><a href="measurement.html#key-takeaways-9"><i class="fa fa-check"></i><b>3.3.7</b> Key takeaways</a></li>
<li class="chapter" data-level="3.3.8" data-path="measurement.html"><a href="measurement.html#exercises-9"><i class="fa fa-check"></i><b>3.3.8</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html"><i class="fa fa-check"></i><b>4</b> Single Factor Experiments</a><ul>
<li class="chapter" data-level="4.1" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html#experiments-in-a-nutshell"><i class="fa fa-check"></i><b>4.1</b> Experiments in a nutshell</a></li>
<li class="chapter" data-level="4.2" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html#distributions"><i class="fa fa-check"></i><b>4.2</b> Distributions</a></li>
<li class="chapter" data-level="4.3" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html#differences-can-arise-by-chance-because-of-sampling"><i class="fa fa-check"></i><b>4.3</b> Differences can arise by chance because of sampling</a></li>
<li class="chapter" data-level="4.4" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html#what-kind-of-differences-can-chance-produce"><i class="fa fa-check"></i><b>4.4</b> What kind of differences can chance produce?</a></li>
<li class="chapter" data-level="4.5" data-path="single-factor-experiments.html"><a href="single-factor-experiments.html#chance-can-produce-differences-between-conditions-in-an-experiment"><i class="fa fa-check"></i><b>4.5</b> Chance can produce differences between conditions in an experiment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="level-designs-and-t-tests.html"><a href="level-designs-and-t-tests.html"><i class="fa fa-check"></i><b>5</b> 2 level designs and t-tests</a><ul>
<li class="chapter" data-level="5.1" data-path="level-designs-and-t-tests.html"><a href="level-designs-and-t-tests.html#an-example"><i class="fa fa-check"></i><b>5.1</b> An example</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="simulating-the-null.html"><a href="simulating-the-null.html"><i class="fa fa-check"></i><b>6</b> Simulating the null</a></li>
<li class="chapter" data-level="7" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html"><i class="fa fa-check"></i><b>7</b> Simulating real differences</a><ul>
<li class="chapter" data-level="7.1" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#an-example-psychology-experiment"><i class="fa fa-check"></i><b>7.1</b> An example Psychology Experiment</a></li>
<li class="chapter" data-level="7.2" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#more-experimental-basics"><i class="fa fa-check"></i><b>7.2</b> More Experimental Basics</a><ul>
<li class="chapter" data-level="7.2.1" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#what-is-an-experiment"><i class="fa fa-check"></i><b>7.2.1</b> What Is an Experiment?</a></li>
<li class="chapter" data-level="7.2.2" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#four-big-validities"><i class="fa fa-check"></i><b>7.2.2</b> Four Big Validities</a></li>
<li class="chapter" data-level="7.2.3" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#internal-validity"><i class="fa fa-check"></i><b>7.2.3</b> Internal Validity</a></li>
<li class="chapter" data-level="7.2.4" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#external-validity"><i class="fa fa-check"></i><b>7.2.4</b> External Validity</a></li>
<li class="chapter" data-level="7.2.5" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#construct-validity"><i class="fa fa-check"></i><b>7.2.5</b> Construct Validity</a></li>
<li class="chapter" data-level="7.2.6" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#statistical-validity"><i class="fa fa-check"></i><b>7.2.6</b> Statistical Validity</a></li>
<li class="chapter" data-level="7.2.7" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#prioritizing-validities"><i class="fa fa-check"></i><b>7.2.7</b> Prioritizing Validities</a></li>
<li class="chapter" data-level="7.2.8" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#manipulation-of-the-independent-variable"><i class="fa fa-check"></i><b>7.2.8</b> Manipulation of the Independent Variable</a></li>
<li class="chapter" data-level="7.2.9" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#control-of-extraneous-variables"><i class="fa fa-check"></i><b>7.2.9</b> Control of Extraneous Variables</a></li>
<li class="chapter" data-level="7.2.10" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#extraneous-variables-as-noise"><i class="fa fa-check"></i><b>7.2.10</b> Extraneous Variables as “Noise”</a></li>
<li class="chapter" data-level="7.2.11" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#extraneous-variables-as-confounding-variables"><i class="fa fa-check"></i><b>7.2.11</b> Extraneous Variables as Confounding Variables</a></li>
<li class="chapter" data-level="7.2.12" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section"><i class="fa fa-check"></i><b>7.2.12</b> </a></li>
<li class="chapter" data-level="7.2.13" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section-1"><i class="fa fa-check"></i><b>7.2.13</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#experimental-design"><i class="fa fa-check"></i><b>7.3</b> Experimental Design</a><ul>
<li class="chapter" data-level="7.3.1" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#between-subjects-experiments"><i class="fa fa-check"></i><b>7.3.1</b> Between-Subjects Experiments</a></li>
<li class="chapter" data-level="7.3.2" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#random-assignment"><i class="fa fa-check"></i><b>7.3.2</b> Random Assignment</a></li>
<li class="chapter" data-level="7.3.3" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#treatment-and-control-conditions"><i class="fa fa-check"></i><b>7.3.3</b> Treatment and Control Conditions</a></li>
<li class="chapter" data-level="7.3.4" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#within-subjects-experiments"><i class="fa fa-check"></i><b>7.3.4</b> Within-Subjects Experiments</a></li>
<li class="chapter" data-level="7.3.5" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#carryover-effects-and-counterbalancing"><i class="fa fa-check"></i><b>7.3.5</b> Carryover Effects and Counterbalancing</a></li>
<li class="chapter" data-level="7.3.6" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#simultaneous-within-subjects-designs"><i class="fa fa-check"></i><b>7.3.6</b> Simultaneous Within-Subjects Designs</a></li>
<li class="chapter" data-level="7.3.7" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#between-subjects-or-within-subjects"><i class="fa fa-check"></i><b>7.3.7</b> Between-Subjects or Within-Subjects?</a></li>
<li class="chapter" data-level="7.3.8" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section-2"><i class="fa fa-check"></i><b>7.3.8</b> </a></li>
<li class="chapter" data-level="7.3.9" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section-3"><i class="fa fa-check"></i><b>7.3.9</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#conducting-experiments"><i class="fa fa-check"></i><b>7.4</b> Conducting Experiments</a><ul>
<li class="chapter" data-level="7.4.1" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#recruiting-participants"><i class="fa fa-check"></i><b>7.4.1</b> Recruiting Participants</a></li>
<li class="chapter" data-level="7.4.2" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#standardizing-the-procedure"><i class="fa fa-check"></i><b>7.4.2</b> Standardizing the Procedure</a></li>
<li class="chapter" data-level="7.4.3" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#record-keeping"><i class="fa fa-check"></i><b>7.4.3</b> Record Keeping</a></li>
<li class="chapter" data-level="7.4.4" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#pilot-testing"><i class="fa fa-check"></i><b>7.4.4</b> Pilot Testing</a></li>
<li class="chapter" data-level="7.4.5" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section-4"><i class="fa fa-check"></i><b>7.4.5</b> </a></li>
<li class="chapter" data-level="7.4.6" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#section-5"><i class="fa fa-check"></i><b>7.4.6</b> </a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#single-factor-designs-with-2-levels"><i class="fa fa-check"></i><b>7.5</b> Single Factor Designs with 2 levels</a><ul>
<li class="chapter" data-level="7.5.1" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#the-basic-empirical-question-is-there-a-difference"><i class="fa fa-check"></i><b>7.5.1</b> The basic empirical question: Is there a difference?</a></li>
<li class="chapter" data-level="7.5.2" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#chance-and-change"><i class="fa fa-check"></i><b>7.5.2</b> Chance and Change</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="simulating-real-differences.html"><a href="simulating-real-differences.html#single-factor-designs-with-multiple-levels"><i class="fa fa-check"></i><b>7.6</b> Single Factor Designs with multiple levels</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>8</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Research methods for Psychology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simulating-real-differences" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Simulating real differences</h1>
<p>Imagine a between-subjects experiment on 20 students (10 in each group), asking whether studying or not changes test performance on a midterm. The IV is studying (studying vs. not studying), and the DV is test performance (percentage on the midterm). We assume that studying is important for passing a test, so the group who studies should have higher test scores than the group who doesn’t. We can simulate this experiment by randomly sampling scores for the study group from a distribution with a higher mean than the no study group.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>For example, the histograms on the right show that the sample scores in the study group will come from a distribution with mean = 80, and standard deviation = 5; and the sample scores in the no study group will come from a distribution with mean = 65, and standard deviation 5. The simulated scores in the experiment are in the table below:</p>
<table>
<thead>
<tr class="header">
<th align="right">study</th>
<th align="right">no_study</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">73</td>
<td align="right">67</td>
</tr>
<tr class="even">
<td align="right">80</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">78</td>
<td align="right">63</td>
</tr>
<tr class="even">
<td align="right">83</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="right">84</td>
<td align="right">63</td>
</tr>
<tr class="even">
<td align="right">67</td>
<td align="right">59</td>
</tr>
<tr class="odd">
<td align="right">78</td>
<td align="right">57</td>
</tr>
<tr class="even">
<td align="right">81</td>
<td align="right">71</td>
</tr>
<tr class="odd">
<td align="right">90</td>
<td align="right">57</td>
</tr>
<tr class="even">
<td align="right">77</td>
<td align="right">57</td>
</tr>
</tbody>
</table>
<p>The group means are:</p>
<table>
<thead>
<tr class="header">
<th align="left">condition</th>
<th align="right">scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">no_study</td>
<td align="right">62.6</td>
</tr>
<tr class="even">
<td align="left">study</td>
<td align="right">79.1</td>
</tr>
</tbody>
</table>
<p>And, the t-test is:</p>
<pre><code>## 
##  Two Sample t-test
## 
## data:  study and no_study
## t = 6.2698, df = 18, p-value = 6.516e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  10.97112 22.02888
## sample estimates:
## mean of x mean of y 
##      79.1      62.6</code></pre>
<p>The results of the t-test could be reported as follows:</p>
<p>Mean test performance in the study group group (79.1) was significantly higher than mean test performance in the no study group (62.6), t(18) = 6.27, p = 0.</p>
<p>Or, more simply: Students who studied (79.1) had higher averages than students who didn’t study (62.6), t(18) = 6.27, p = 0.</p>
<div id="an-example-psychology-experiment" class="section level2">
<h2><span class="header-section-number">7.1</span> An example Psychology Experiment</h2>
<p>In the late 1960s social psychologists John Darley and Bibb Latané proposed a counter-intuitive hypothesis. The more witnesses there are to an accident or a crime, the less likely any of them is to help the victim (Darley &amp; Latané, 1968).</p>
<p>They also suggested the theory that this phenomenon occurs because each witness feels less responsible for helping—a process referred to as the “diffusion of responsibility.” Darley and Latané noted that their ideas were consistent with many real-world cases. For example, a New York woman named Catherine “Kitty” Genovese was assaulted and murdered while several witnesses evidently failed to help. But Darley and Latané also understood that such isolated cases did not provide convincing evidence for their hypothesized “bystander effect.” There was no way to know, for example, whether any of the witnesses to Kitty Genovese’s murder would have helped had there been fewer of them.</p>
<p>So to test their hypothesis, Darley and Latané created a simulated emergency situation in a laboratory. Each of their university student participants was isolated in a small room and told that he or she would be having a discussion about university life with other students via an intercom system. Early in the discussion, however, one of the students began having what seemed to be an epileptic seizure. Over the intercom came the following: “I could really-er-use some help so if somebody would-er-give me a little h-help-uh-er-er-er-er-er c-could somebody-er- er-help-er-uh-uh-uh (choking sounds)…I’m gonna die-er-er-I’m…gonna die-er-help-er-er-seizure-er- [chokes, then quiet]” (Darley &amp; Latané, 1968, p. 379)2.</p>
<p>In actuality, there were no other students. These comments had been prerecorded and were played back to create the appearance of a real emergency. The key to the study was that some participants were told that the discussion involved only one other student (the victim), others were told that it involved two other students, and still others were told that it included five other students. Because this was the only difference between these three groups of participants, any difference in their tendency to help the victim would have to have been caused by it. And sure enough, the likelihood that the participant left the room to seek help for the “victim” decreased from 85% to 62% to 31% as the number of “witnesses” increased.</p>
<p>The story of Kitty Genovese has been told and retold in numerous psychology textbooks. The standard version is that there were 38 witnesses to the crime, that all of them watched (or listened) for an extended period of time, and that none of them did anything to help. However, recent scholarship suggests that the standard story is inaccurate in many ways (Manning, Levine, &amp; Collins, 2007)3. For example, only six eyewitnesses testified at the trial, none of them was aware that he or she was witnessing a lethal assault, and there have been several reports of witnesses calling the police or even coming to the aid of Kitty Genovese. Although the standard story inspired a long line of research on the bystander effect and the diffusion of responsibility, it may also have directed researchers’ and students’ attention away from other equally interesting and important issues in the psychology of helping—including the conditions in which people do in fact respond collectively to emergency situations.</p>
<p>The research that Darley and Latané conducted was a particular kind of study called an experiment. Experiments are used to determine not only whether there is a meaningful relationship between two variables but also whether the relationship is a causal one that is supported by statistical analysis. For this reason, experiments are one of the most common and useful tools in the psychological researcher’s toolbox. In this chapter, we look at experiments in detail. We will first consider what sets experiments apart from other kinds of studies and why they support causal conclusions while other kinds of studies do not. We then look at two basic ways of designing an experiment—between-subjects designs and within-subjects designs—and discuss their pros and cons. Finally, we consider several important practical issues that arise when conducting experiments.</p>
</div>
<div id="more-experimental-basics" class="section level2">
<h2><span class="header-section-number">7.2</span> More Experimental Basics</h2>
<div id="what-is-an-experiment" class="section level3">
<h3><span class="header-section-number">7.2.1</span> What Is an Experiment?</h3>
<p>As we saw earlier in the book, an experiment is a type of study designed specifically to answer the question of whether there is a causal relationship between two variables. In other words, whether changes in an independent variable cause changes in a dependent variable. Experiments have two fundamental features. The first is that the researchers manipulate, or systematically vary, the level of the independent variable. The different levels of the independent variable are called conditions. For example, in Darley and Latané’s experiment, the independent variable was the number of witnesses that participants believed to be present. The researchers manipulated this independent variable by telling participants that there were either one, two, or five other students involved in the discussion, thereby creating three conditions. For a new researcher, it is easy to confuse these terms by believing there are three independent variables in this situation: one, two, or five students involved in the discussion, but there is actually only one independent variable (number of witnesses) with three different conditions (one, two or five students). The second fundamental feature of an experiment is that the researcher controls, or minimizes the variability in, variables other than the independent and dependent variable. These other variables are called extraneous variables. Darley and Latané tested all their participants in the same room, exposed them to the same emergency situation, and so on. They also randomly assigned their participants to conditions so that the three groups would be similar to each other to begin with. Notice that although the words manipulation and control have similar meanings in everyday language, researchers make a clear distinction between them. They manipulate the independent variable by systematically changing its levels and control other variables by holding them constant.</p>
</div>
<div id="four-big-validities" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Four Big Validities</h3>
<p>When we read about psychology experiments with a critical view, one question to ask is “is this study valid?” However, that question is not as straightforward as it seems because in psychology, there are many different kinds of validities. Researchers have focused on four validities to help assess whether an experiment is sound (Judd &amp; Kenny, 1981; Morling, 2014): internal validity, external validity, construct validity, and statistical validity. We will explore each validity in depth.</p>
</div>
<div id="internal-validity" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Internal Validity</h3>
<p>Recall that two variables being statistically related does not necessarily mean that one causes the other. “Correlation does not imply causation.” For example, if it were the case that people who exercise regularly are happier than people who do not exercise regularly, this implication would not necessarily mean that exercising increases people’s happiness. It could mean instead that greater happiness causes people to exercise (the directionality problem) or that something like better physical health causes people to exercise and be happier (the third-variable problem).</p>
<p>The purpose of an experiment, however, is to show that two variables are statistically related and to do so in a way that supports the conclusion that the independent variable caused any observed differences in the dependent variable. The logic is based on this assumption : If the researcher creates two or more highly similar conditions and then manipulates the independent variable to produce just one difference between them, then any later difference between the conditions must have been caused by the independent variable. For example, because the only difference between Darley and Latané’s conditions was the number of students that participants believed to be involved in the discussion, this difference in belief must have been responsible for differences in helping between the conditions.</p>
<p>An empirical study is said to be high in internal validity if the way it was conducted supports the conclusion that the independent variable caused any observed differences in the dependent variable. Thus experiments are high in internal validity because the way they are conducted—with the manipulation of the independent variable and the control of extraneous variables—provides strong support for causal conclusions.</p>
</div>
<div id="external-validity" class="section level3">
<h3><span class="header-section-number">7.2.4</span> External Validity</h3>
<p>At the same time, the way that experiments are conducted sometimes leads to a different kind of criticism. Specifically, the need to manipulate the independent variable and control extraneous variables means that experiments are often conducted under conditions that seem artificial (Bauman, McGraw, Bartels, &amp; Warren, 2014)3. In many psychology experiments, the participants are all undergraduate students and come to a classroom or laboratory to fill out a series of paper-and-pencil questionnaires or to perform a carefully designed computerized task. Consider, for example, an experiment in which researcher Barbara Fredrickson and her colleagues had undergraduate students come to a laboratory on campus and complete a math test while wearing a swimsuit (Fredrickson, Roberts, Noll, Quinn, &amp; Twenge, 1998)4. At first, this manipulation might seem silly. When will undergraduate students ever have to complete math tests in their swimsuits outside of this experiment?</p>
<p>The issue we are confronting is that of external validity. An empirical study is high in external validity if the way it was conducted supports generalizing the results to people and situations beyond those actually studied. As a general rule, studies are higher in external validity when the participants and the situation studied are similar to those that the researchers want to generalize to and participants encounter everyday, often described as mundane realism. Imagine, for example, that a group of researchers is interested in how shoppers in large grocery stores are affected by whether breakfast cereal is packaged in yellow or purple boxes. Their study would be high in external validity and have high mundane realism if they studied the decisions of ordinary people doing their weekly shopping in a real grocery store. If the shoppers bought much more cereal in purple boxes, the researchers would be fairly confident that this increase would be true for other shoppers in other stores. Their study would be relatively low in external validity, however, if they studied a sample of undergraduate students in a laboratory at a selective university who merely judged the appeal of various colors presented on a computer screen; however, this study would have high psychological realism where the same mental process is used in both the laboratory and in the real world. If the students judged purple to be more appealing than yellow, the researchers would not be very confident that this preference is relevant to grocery shoppers’ cereal-buying decisions because of low external validity but they could be confident that the visual processing of colors has high psychological realism.</p>
<p>We should be careful, however, not to draw the blanket conclusion that experiments are low in external validity. One reason is that experiments need not seem artificial. Consider that Darley and Latané’s experiment provided a reasonably good simulation of a real emergency situation. Or consider-field experiments that are conducted entirely outside the laboratory. In one such experiment, Robert Cialdini and his colleagues studied whether hotel guests choose to reuse their towels for a second day as opposed to having them washed as a way of conserving water and energy (Cialdini, 2005)5. These researchers manipulated the message on a card left in a large sample of hotel rooms. One version of the message emphasized showing respect for the environment, another emphasized that the hotel would donate a portion of their savings to an environmental cause, and a third emphasized that most hotel guests choose to reuse their towels. The result was that guests who received the message that most hotel guests choose to reuse their towels reused their own towels substantially more often than guests receiving either of the other two messages. Given the way they conducted their study, it seems very likely that their result would hold true for other guests in other hotels.</p>
<p>A second reason not to draw the blanket conclusion that experiments are low in external validity is that they are often conducted to learn about psychological processes that are likely to operate in a variety of people and situations. Let us return to the experiment by Fredrickson and colleagues. They found that the women in their study, but not the men, performed worse on the math test when they were wearing swimsuits. They argued that this gender difference was due to women’s greater tendency to objectify themselves—to think about themselves from the perspective of an outside observer—which diverts their attention away from other tasks. They argued, furthermore, that this process of self-objectification and its effect on attention is likely to operate in a variety of women and situations—even if none of them ever finds herself taking a math test in her swimsuit.</p>
</div>
<div id="construct-validity" class="section level3">
<h3><span class="header-section-number">7.2.5</span> Construct Validity</h3>
<p>In addition to the generalizability of the results of an experiment, another element to scrutinize in a study is the quality of the experiment’s manipulations, or the construct validity. The research question that Darley and Latané started with is “does helping behavior become diffused?” They hypothesized that participants in a lab would be less likely to help when they believed there were more potential helpers besides themselves. This conversion from research question to experiment design is called operationalization (see Chapter 2 for more information about the operational definition). Darley and Latané operationalized the independent variable of diffusion of responsibility by increasing the number of potential helpers. In evaluating this design, we would say that the construct validity was very high because the experiment’s manipulations very clearly speak to the research question; there was a crisis, a way for the participant to help, and increasing the number of other students involved in the discussion, they provided a way to test diffusion.</p>
<p>What if the number of conditions in Darley and Latané’s study changed? Consider if there were only two conditions: one student involved in the discussion or two. Even though we may see a decrease in helping by adding another person, it may not be a clear demonstration of diffusion of responsibility, just merely the presence of others. We might think it was a form of Bandura’s social inhibition (discussed in Chapter 4). The construct validity would be lower. However, had there been five conditions, perhaps we would see the decrease continue with more people in the discussion or perhaps it would plateau after a certain number of people. In that situation, we may not necessarily be learning more about diffusion of responsibility or it may become a different phenomenon. By adding more conditions, the construct validity may not get higher. When designing your own experiment, consider how well the research question is operationalized your study.</p>
</div>
<div id="statistical-validity" class="section level3">
<h3><span class="header-section-number">7.2.6</span> Statistical Validity</h3>
<p>A common critique of experiments is that a study did not have enough participants. The main reason for this criticism is that it is difficult to generalize about a population from a small sample. At the outset, it seems as though this critique is about external validity but there are studies where small sample sizes are not a problem (Chapter 11 will discuss how small samples, even of only 1 person, are still very illuminating for psychology research). Therefore, small sample sizes are actually a critique of statistical validity. The statistical validity speaks to whether the statistics conducted in the study support the conclusions that are made.</p>
<p>Proper statistical analysis should be conducted on the data to determine whether the difference or relationship that was predicted was found. The number of conditions and the number of total participants will determine the overall size of the effect. With this information, a power analysis can be conducted to ascertain whether you are likely to find a real difference. When designing a study, it is best to think about the power analysis so that the appropriate number of participants can be recruited and tested (more on effect sizes in Chapter 12). To design a statistically valid experiment, thinking about the statistical tests at the beginning of the design will help ensure the results can be believed.</p>
</div>
<div id="prioritizing-validities" class="section level3">
<h3><span class="header-section-number">7.2.7</span> Prioritizing Validities</h3>
<p>These four big validities–internal, external, construct, and statistical–are useful to keep in mind when both reading about other experiments and designing your own. However, researchers must prioritize and often it is not possible to have high validity in all four areas. In Cialdini’s study on towel usage in hotels, the external validity was high but the statistical validity was more modest. This discrepancy does not invalidate the study but it shows where there may be room for improvement for future follow-up studies (Goldstein, Cialdini, &amp; Griskevicius, 2008)6. Morling (2014) points out that most psychology studies have high internal and construct validity but sometimes sacrifice external validity.</p>
</div>
<div id="manipulation-of-the-independent-variable" class="section level3">
<h3><span class="header-section-number">7.2.8</span> Manipulation of the Independent Variable</h3>
<p>Again, to manipulate an independent variable means to change its level systematically so that different groups of participants are exposed to different levels of that variable, or the same group of participants is exposed to different levels at different times. For example, to see whether expressive writing affects people’s health, a researcher might instruct some participants to write about traumatic experiences and others to write about neutral experiences. As discussed earlier in this chapter, the different levels of the independent variable are referred to as conditions, and researchers often give the conditions short descriptive names to make it easy to talk and write about them. In this case, the conditions might be called the “traumatic condition” and the “neutral condition.”</p>
<p>Notice that the manipulation of an independent variable must involve the active intervention of the researcher. Comparing groups of people who differ on the independent variable before the study begins is not the same as manipulating that variable. For example, a researcher who compares the health of people who already keep a journal with the health of people who do not keep a journal has not manipulated this variable and therefore not conducted an experiment. This distinction is important because groups that already differ in one way at the beginning of a study are likely to differ in other ways too. For example, people who choose to keep journals might also be more conscientious, more introverted, or less stressed than people who do not. Therefore, any observed difference between the two groups in terms of their health might have been caused by whether or not they keep a journal, or it might have been caused by any of the other differences between people who do and do not keep journals. Thus the active manipulation of the independent variable is crucial for eliminating the third-variable problem.</p>
<p>Of course, there are many situations in which the independent variable cannot be manipulated for practical or ethical reasons and therefore an experiment is not possible. For example, whether or not people have a significant early illness experience cannot be manipulated, making it impossible to conduct an experiment on the effect of early illness experiences on the development of hypochondriasis. This caveat does not mean it is impossible to study the relationship between early illness experiences and hypochondriasis—only that it must be done using nonexperimental approaches. We will discuss this type of methodology in detail later in the book.</p>
<p>In many experiments, the independent variable is a construct that can only be manipulated indirectly. For example, a researcher might try to manipulate participants’ stress levels indirectly by telling some of them that they have five minutes to prepare a short speech that they will then have to give to an audience of other participants. In such situations, researchers often include a manipulation check in their procedure. A manipulation check is a separate measure of the construct the researcher is trying to manipulate. For example, researchers trying to manipulate participants’ stress levels might give them a paper-and-pencil stress questionnaire or take their blood pressure—perhaps right after the manipulation or at the end of the procedure—to verify that they successfully manipulated this variable.</p>
</div>
<div id="control-of-extraneous-variables" class="section level3">
<h3><span class="header-section-number">7.2.9</span> Control of Extraneous Variables</h3>
<p>As we have seen previously in the chapter, an extraneous variable is anything that varies in the context of a study other than the independent and dependent variables. In an experiment on the effect of expressive writing on health, for example, extraneous variables would include participant variables (individual differences) such as their writing ability, their diet, and their shoe size. They would also include situational or task variables such as the time of day when participants write, whether they write by hand or on a computer, and the weather. Extraneous variables pose a problem because many of them are likely to have some effect on the dependent variable. For example, participants’ health will be affected by many things other than whether or not they engage in expressive writing. This influencing factor can make it difficult to separate the effect of the independent variable from the effects of the extraneous variables, which is why it is important to control extraneous variables by holding them constant.</p>
</div>
<div id="extraneous-variables-as-noise" class="section level3">
<h3><span class="header-section-number">7.2.10</span> Extraneous Variables as “Noise”</h3>
<p>Extraneous variables make it difficult to detect the effect of the independent variable in two ways. One is by adding variability or “noise” to the data. Imagine a simple experiment on the effect of mood (happy vs. sad) on the number of happy childhood events people are able to recall. Participants are put into a negative or positive mood (by showing them a happy or sad video clip) and then asked to recall as many happy childhood events as they can. The two leftmost columns of Table 6.1 show what the data might look like if there were no extraneous variables and the number of happy childhood events participants recalled was affected only by their moods. Every participant in the happy mood condition recalled exactly four happy childhood events, and every participant in the sad mood condition recalled exactly three. The effect of mood here is quite obvious. In reality, however, the data would probably look more like those in the two rightmost columns of Table 6.1. Even in the happy mood condition, some participants would recall fewer happy memories because they have fewer to draw on, use less effective recall strategies, or are less motivated. And even in the sad mood condition, some participants would recall more happy childhood memories because they have more happy memories to draw on, they use more effective recall strategies, or they are more motivated. Although the mean difference between the two groups is the same as in the idealized data, this difference is much less obvious in the context of the greater variability in the data. Thus one reason researchers try to control extraneous variables is so their data look more like the idealized data in Table 6.1, which makes the effect of the independent variable easier to detect (although real data never look quite that good).</p>
<div class="figure">
<embed src="figures/C6noisydata.pdf" />
<p class="caption">Hypothetical Noiseless Data and Realistic Noisy Data</p>
</div>
<p>[fig:noisydata]</p>
<p>One way to control extraneous variables is to hold them constant. This technique can mean holding situation or task variables constant by testing all participants in the same location, giving them identical instructions, treating them in the same way, and so on. It can also mean holding participant variables constant. For example, many studies of language limit participants to right-handed people, who generally have their language areas isolated in their left cerebral hemispheres. Left-handed people are more likely to have their language areas isolated in their right cerebral hemispheres or distributed across both hemispheres, which can change the way they process language and thereby add noise to the data.</p>
<p>In principle, researchers can control extraneous variables by limiting participants to one very specific category of person, such as 20-year-old, heterosexual, female, right-handed psychology majors. The obvious downside to this approach is that it would lower the external validity of the study—in particular, the extent to which the results can be generalized beyond the people actually studied. For example, it might be unclear whether results obtained with a sample of younger heterosexual women would apply to older homosexual men. In many situations, the advantages of a diverse sample outweigh the reduction in noise achieved by a homogeneous one.</p>
</div>
<div id="extraneous-variables-as-confounding-variables" class="section level3">
<h3><span class="header-section-number">7.2.11</span> Extraneous Variables as Confounding Variables</h3>
<p>The second way that extraneous variables can make it difficult to detect the effect of the independent variable is by becoming confounding variables. A confounding variable is an extraneous variable that differs on average across levels of the independent variable. For example, in almost all experiments, participants’ intelligence quotients (IQs) will be an extraneous variable. But as long as there are participants with lower and higher IQs at each level of the independent variable so that the average IQ is roughly equal, then this variation is probably acceptable (and may even be desirable). What would be bad, however, would be for participants at one level of the independent variable to have substantially lower IQs on average and participants at another level to have substantially higher IQs on average. In this case, IQ would be a confounding variable.</p>
<div class="figure">
<embed src="figures/C6confound.pdf" />
<p class="caption">Hypothetical Results From a Study on the Effect of Mood on Memory. Because IQ also differs across conditions, it is a confounding variable.</p>
</div>
<p>[fig:confound]</p>
<p>To confound means to confuse, and this effect is exactly why confounding variables are undesirable. Because they differ across conditions—just like the independent variable—they provide an alternative explanation for any observed difference in the dependent variable. Figure 6.1 shows the results of a hypothetical study, in which participants in a positive mood condition scored higher on a memory task than participants in a negative mood condition. But if IQ is a confounding variable—with participants in the positive mood condition having higher IQs on average than participants in the negative mood condition—then it is unclear whether it was the positive moods or the higher IQs that caused participants in the first condition to score higher. One way to avoid confounding variables is by holding extraneous variables constant. For example, one could prevent IQ from becoming a confounding variable by limiting participants only to those with IQs of exactly 100. But this approach is not always desirable for reasons we have already discussed. A second and much more general approach—random assignment to conditions—will be discussed in detail shortly.</p>
</div>
<div id="section" class="section level3">
<h3><span class="header-section-number">7.2.12</span> </h3>
<ul>
<li><p>An experiment is a type of empirical study that features the manipulation of an independent variable, the measurement of a dependent variable, and control of extraneous variables.</p></li>
<li><p>Studies are high in internal validity to the extent that the way they are conducted supports the conclusion that the independent variable caused any observed differences in the dependent variable. Experiments are generally high in internal validity because of the manipulation of the independent variable and control of extraneous variables.</p></li>
<li><p>Studies are high in external validity to the extent that the result can be generalized to people and situations beyond those actually studied. Although experiments can seem “artificial”—and low in external validity—it is important to consider whether the psychological processes under study are likely to operate in other people and situations.</p></li>
</ul>
</div>
<div id="section-1" class="section level3">
<h3><span class="header-section-number">7.2.13</span> </h3>
<ol style="list-style-type: decimal">
<li><p>Practice: List five variables that can be manipulated by the researcher in an experiment. List five variables that cannot be manipulated by the researcher in an experiment.</p></li>
<li><p>Practice: For each of the following topics, decide whether that topic could be studied using an experimental research design and explain why or why not.</p>
<ul>
<li><p>Effect of parietal lobe damage on people’s ability to do basic arithmetic.</p></li>
<li><p>Effect of being clinically depressed on the number of close friendships people have.</p></li>
<li><p>Effect of group training on the social skills of teenagers with Asperger’s syndrome.</p></li>
<li><p>Effect of paying people to take an IQ test on their performance on that test.</p></li>
</ul></li>
</ol>
</div>
</div>
<div id="experimental-design" class="section level2">
<h2><span class="header-section-number">7.3</span> Experimental Design</h2>
<p>In this section, we look at some different ways to design an experiment. The primary distinction we will make is between approaches in which each participant experiences one level of the independent variable and approaches in which each participant experiences all levels of the independent variable. The former are called between-subjects experiments and the latter are called within-subjects experiments.</p>
<div id="between-subjects-experiments" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Between-Subjects Experiments</h3>
<p>In a between-subjects experiment, each participant is tested in only one condition. For example, a researcher with a sample of 100 university students might assign half of them to write about a traumatic event and the other half write about a neutral event. Or a researcher with a sample of 60 people with severe agoraphobia (fear of open spaces) might assign 20 of them to receive each of three different treatments for that disorder. It is essential in a between- subjects experiment that the researcher assign participants to conditions so that the different groups are, on average, highly similar to each other. Those in a trauma condition and a neutral condition, for example, should include a similar proportion of men and women, and they should have similar average intelligence quotients (IQs), similar average levels of motivation, similar average numbers of health problems, and so on. This matching is a matter of controlling these extraneous participant variables across conditions so that they do not become confounding variables.</p>
</div>
<div id="random-assignment" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Random Assignment</h3>
<p>The primary way that researchers accomplish this kind of control of extraneous variables across conditions is called random assignment, which means using a random process to decide which participants are tested in which conditions. Do not confuse random assignment with random sampling. Random sampling is a method for selecting a sample from a population, and it is rarely used in psychological research. Random assignment is a method for assigning participants in a sample to the different conditions, and it is an important element of all experimental research in psychology and other fields too.</p>
<p>In its strictest sense, random assignment should meet two criteria. One is that each participant has an equal chance of being assigned to each condition (e.g., a 50% chance of being assigned to each of two conditions). The second is that each participant is assigned to a condition independently of other participants. Thus one way to assign participants to two conditions would be to flip a coin for each one. If the coin lands heads, the participant is assigned to Condition A, and if it lands tails, the participant is assigned to Condition B. For three conditions, one could use a computer to generate a random integer from 1 to 3 for each participant. If the integer is 1, the participant is assigned to Condition A; if it is 2, the participant is assigned to Condition B; and if it is 3, the participant is assigned to Condition C. In practice, a full sequence of conditions—one for each participant expected to be in the experiment—is usually created ahead of time, and each new participant is assigned to the next condition in the sequence as he or she is tested. When the procedure is computerized, the computer program often handles the random assignment.</p>
<p>One problem with coin flipping and other strict procedures for random assignment is that they are likely to result in unequal sample sizes in the different conditions. Unequal sample sizes are generally not a serious problem, and you should never throw away data you have already collected to achieve equal sample sizes. However, for a fixed number of participants, it is statistically most efficient to divide them into equal-sized groups. It is standard practice, therefore, to use a kind of modified random assignment that keeps the number of participants in each group as similar as possible. One approach is block randomization. In block randomization, all the conditions occur once in the sequence before any of them is repeated. Then they all occur again before any of them is repeated again. Within each of these “blocks,” the conditions occur in a random order. Again, the sequence of conditions is usually generated before any participants are tested, and each new participant is assigned to the next condition in the sequence. Table 6.2 shows such a sequence for assigning nine participants to three conditions. The Research Randomizer website <a href="http://www.randomizer.org" class="uri">http://www.randomizer.org</a> will generate block randomization sequences for any number of participants and conditions. Again, when the procedure is computerized, the computer program often handles the block randomization.</p>
<div class="figure">
<embed src="figures/C6blockRandomization.pdf" />
<p class="caption">Block Randomization Sequence for Assigning Nine Participants to Three Conditions</p>
</div>
<p>[fig:Bargraph]</p>
<p>Random assignment is not guaranteed to control all extraneous variables across conditions. It is always possible that just by chance, the participants in one condition might turn out to be substantially older, less tired, more motivated, or less depressed on average than the participants in another condition. However, there are some reasons that this possibility is not a major concern. One is that random assignment works better than one might expect, especially for large samples. Another is that the inferential statistics that researchers use to decide whether a difference between groups reflects a difference in the population takes the “fallibility” of random assignment into account. Yet another reason is that even if random assignment does result in a confounding variable and therefore produces misleading results, this confound is likely to be detected when the experiment is replicated. The upshot is that random assignment to conditions—although not infallible in terms of controlling extraneous variables—is always considered a strength of a research design.</p>
</div>
<div id="treatment-and-control-conditions" class="section level3">
<h3><span class="header-section-number">7.3.3</span> Treatment and Control Conditions</h3>
<p>Between-subjects experiments are often used to determine whether a treatment works. In psychological research, a treatment is any intervention meant to change people’s behavior for the better. This intervention includes psychotherapies and medical treatments for psychological disorders but also interventions designed to improve learning, promote conservation, reduce prejudice, and so on. To determine whether a treatment works, participants are randomly assigned to either a treatment condition, in which they receive the treatment, or a control condition, in which they do not receive the treatment. If participants in the treatment condition end up better off than participants in the control condition—for example, they are less depressed, learn faster, conserve more, express less prejudice—then the researcher can conclude that the treatment works. In research on the effectiveness of psychotherapies and medical treatments, this type of experiment is often called a randomized clinical trial.</p>
<p>There are different types of control conditions. In a no-treatment control condition, participants receive no treatment whatsoever. One problem with this approach, however, is the existence of placebo effects. A placebo is a simulated treatment that lacks any active ingredient or element that should make it effective, and a placebo effect is a positive effect of such a treatment. Many folk remedies that seem to work—such as eating chicken soup for a cold or placing soap under the bed sheets to stop nighttime leg cramps—are probably nothing more than placebos. Although placebo effects are not well understood, they are probably driven primarily by people’s expectations that they will improve. Having the expectation to improve can result in reduced stress, anxiety, and depression, which can alter perceptions and even improve immune system functioning (Price, Finniss, &amp; Benedetti, 2008)1.</p>
<p>Placebo effects are interesting in their own right (see Note “The Powerful Placebo”), but they also pose a serious problem for researchers who want to determine whether a treatment works. Figure 6.2 shows some hypothetical results in which participants in a treatment condition improved more on average than participants in a no-treatment control condition. If these conditions (the two leftmost bars in Figure 6.2) were the only conditions in this experiment, however, one could not conclude that the treatment worked. It could be instead that participants in the treatment group improved more because they expected to improve, while those in the no-treatment control condition did not.</p>
<p>Fortunately, there are several solutions to this problem. One is to include a placebo control condition, in which participants receive a placebo that looks much like the treatment but lacks the active ingredient or element thought to be responsible for the treatment’s effectiveness. When participants in a treatment condition take a pill, for example, then those in a placebo control condition would take an identical-looking pill that lacks the active ingredient in the treatment (a “sugar pill”). In research on psychotherapy effectiveness, the placebo might involve going to a psychotherapist and talking in an unstructured way about one’s problems. The idea is that if participants in both the treatment and the placebo control groups expect to improve, then any improvement in the treatment group over and above that in the placebo control group must have been caused by the treatment and not by participants’ expectations. This difference is what is shown by a comparison of the two outer bars in Figure 6.2. 1.</p>
<div class="figure">
<embed src="figures/C6placebo.pdf" />
<p class="caption">Hypothetical Results From a Study Including Treatment, No-Treatment, and Placebo Conditions</p>
</div>
<p>[fig:placebo]</p>
<p>Of course, the principle of informed consent requires that participants be told that they will be assigned to either a treatment or a placebo control condition—even though they cannot be told which until the experiment ends. In many cases the participants who had been in the control condition are then offered an opportunity to have the real treatment. An alternative approach is to use a wait-list control condition, in which participants are told that they will receive the treatment but must wait until the participants in the treatment condition have already received it. This disclosure allows researchers to compare participants who have received the treatment with participants who are not currently receiving it but who still expect to improve (eventually). A final solution to the problem of placebo effects is to leave out the control condition completely and compare any new treatment with the best available alternative treatment. For example, a new treatment for simple phobia could be compared with standard exposure therapy. Because participants in both conditions receive a treatment, their expectations about improvement should be similar. This approach also makes sense because once there is an effective treatment, the interesting question about a new treatment is not simply “Does it work?” but “Does it work better than what is already available?</p>
<p>Many people are not surprised that placebos can have a positive effect on disorders that seem fundamentally psychological, including depression, anxiety, and insomnia. However, placebos can also have a positive effect on disorders that most people think of as fundamentally physiological. These include asthma, ulcers, and warts (Shapiro &amp; Shapiro, 1999)2. There is even evidence that placebo surgery—also called “sham surgery”—can be as effective as actual surgery. Medical researcher J. Bruce Moseley and his colleagues conducted a study on the effectiveness of two arthroscopic surgery procedures for osteoarthritis of the knee (Moseley et al., 2002)3. The control participants in this study were prepped for surgery, received a tranquilizer, and even received three small incisions in their knees. But they did not receive the actual arthroscopic surgical procedure. The surprising result was that all participants improved in terms of both knee pain and function, and the sham surgery group improved just as much as the treatment groups. According to the researchers, “This study provides strong evidence that arthroscopic lavage with or without débridement [the surgical procedures used] is not better than and appears to be equivalent to a placebo procedure in improving knee pain and self-reported function” (p. 85).</p>
</div>
<div id="within-subjects-experiments" class="section level3">
<h3><span class="header-section-number">7.3.4</span> Within-Subjects Experiments</h3>
<p>In a within-subjects experiment, each participant is tested under all conditions. Consider an experiment on the effect of a defendant’s physical attractiveness on judgments of his guilt. Again, in a between-subjects experiment, one group of participants would be shown an attractive defendant and asked to judge his guilt, and another group of participants would be shown an unattractive defendant and asked to judge his guilt. In a within-subjects experiment, however, the same group of participants would judge the guilt of both an attractive and an unattractive defendant.</p>
<p>The primary advantage of this approach is that it provides maximum control of extraneous participant variables. Participants in all conditions have the same mean IQ, same socioeconomic status, same number of siblings, and so on—because they are the very same people. Within-subjects experiments also make it possible to use statistical procedures that remove the effect of these extraneous participant variables on the dependent variable and therefore make the data less “noisy” and the effect of the independent variable easier to detect. We will look more closely at this idea later in the book. However, not all experiments can use a within-subjects design nor would it be desirable to.</p>
</div>
<div id="carryover-effects-and-counterbalancing" class="section level3">
<h3><span class="header-section-number">7.3.5</span> Carryover Effects and Counterbalancing</h3>
<p>The primary disadvantage of within-subjects designs is that they can result in carryover effects. A carryover effect is an effect of being tested in one condition on participants’ behavior in later conditions. One type of carryover effect is a practice effect, where participants perform a task better in later conditions because they have had a chance to practice it. Another type is a fatigue effect, where participants perform a task worse in later conditions because they become tired or bored. Being tested in one condition can also change how participants perceive stimuli or interpret their task in later conditions. This type of effect is called a context effect. For example, an average-looking defendant might be judged more harshly when participants have just judged an attractive defendant than when they have just judged an unattractive defendant. Within-subjects experiments also make it easier for participants to guess the hypothesis. For example, a participant who is asked to judge the guilt of an attractive defendant and then is asked to judge the guilt of an unattractive defendant is likely to guess that the hypothesis is that defendant attractiveness affects judgments of guilt. This knowledge could lead the participant to judge the unattractive defendant more harshly because he thinks this is what he is expected to do. Or it could make participants judge the two defendants similarly in an effort to be “fair.”</p>
<p>Carryover effects can be interesting in their own right. (Does the attractiveness of one person depend on the attractiveness of other people that we have seen recently?) But when they are not the focus of the research, carryover effects can be problematic. Imagine, for example, that participants judge the guilt of an attractive defendant and then judge the guilt of an unattractive defendant. If they judge the unattractive defendant more harshly, this might be because of his unattractiveness. But it could be instead that they judge him more harshly because they are becoming bored or tired. In other words, the order of the conditions is a confounding variable. The attractive condition is always the first condition and the unattractive condition the second. Thus any difference between the conditions in terms of the dependent variable could be caused by the order of the conditions and not the independent variable itself.</p>
<p>There is a solution to the problem of order effects, however, that can be used in many situations. It is counterbalancing, which means testing different participants in different orders. For example, some participants would be tested in the attractive defendant condition followed by the unattractive defendant condition, and others would be tested in the unattractive condition followed by the attractive condition. With three conditions, there would be six different orders (ABC, ACB, BAC, BCA, CAB, and CBA), so some participants would be tested in each of the six orders. With counterbalancing, participants are assigned to orders randomly, using the techniques we have already discussed. Thus random assignment plays an important role in within-subjects designs just as in between- subjects designs. Here, instead of randomly assigning to conditions, they are randomly assigned to different orders of conditions. In fact, it can safely be said that if a study does not involve random assignment in one form or another, it is not an experiment.</p>
<p>An efficient way of counterbalancing is through a Latin square design which randomizes through having equal rows and columns. For example, if you have four treatments, you must have four versions. Like a Sudoku puzzle, no treatment can repeat in a row or column. For four versions of four treatments, the Latin square design would look like the table to the right.</p>
<div class="figure">
<embed src="figures/C6counterbalance.pdf" />
<p class="caption">Latin Square for four variables</p>
</div>
<p>[fig:latin]</p>
<p>There are two ways to think about what counterbalancing accomplishes. One is that it controls the order of conditions so that it is no longer a confounding variable. Instead of the attractive condition always being first and the unattractive condition always being second, the attractive condition comes first for some participants and second for others. Likewise, the unattractive condition comes first for some participants and second for others. Thus any overall difference in the dependent variable between the two conditions cannot have been caused by the order of conditions. A second way to think about what counterbalancing accomplishes is that if there are carryover effects, it makes it possible to detect them. One can analyze the data separately for each order to see whether it had an effect.</p>
<p>Researcher Michael Birnbaum has argued that the lack of context provided by between-subjects designs is often a bigger problem than the context effects created by within-subjects designs. To demonstrate this problem, he asked participants to rate two numbers on how large they were on a scale of 1-to-10 where 1 was “very very small” and 10 was “very very large”. One group of participants were asked to rate the number 9 and another group was asked to rate the number 221 (Birnbaum, 1999). Participants in this between-subjects design gave the number 9 a mean rating of 5.13 and the number 221 a mean rating of 3.10. In other words, they rated 9 as larger than 221! According to Birnbaum, this difference is because participants spontaneously compared 9 with other one-digit numbers (in which case it is relatively large) and compared 221 with other three-digit numbers (in which case it is relatively small).</p>
</div>
<div id="simultaneous-within-subjects-designs" class="section level3">
<h3><span class="header-section-number">7.3.6</span> Simultaneous Within-Subjects Designs</h3>
<p>So far, we have discussed an approach to within-subjects designs in which participants are tested in one condition at a time. There is another approach, however, that is often used when participants make multiple responses in each condition. Imagine, for example, that participants judge the guilt of 10 attractive defendants and 10 unattractive defendants. Instead of having people make judgments about all 10 defendants of one type followed by all 10 defendants of the other type, the researcher could present all 20 defendants in a sequence that mixed the two types. The researcher could then compute each participant’s mean rating for each type of defendant. Or imagine an experiment designed to see whether people with social anxiety disorder remember negative adjectives (e.g., “stupid,” “incompetent”) better than positive ones (e.g., “happy,” “productive”). The researcher could have participants study a single list that includes both kinds of words and then have them try to recall as many words as possible. The researcher could then count the number of each type of word that was recalled. There are many ways to determine the order in which the stimuli are presented, but one common way is to generate a different random order for each participant.</p>
</div>
<div id="between-subjects-or-within-subjects" class="section level3">
<h3><span class="header-section-number">7.3.7</span> Between-Subjects or Within-Subjects?</h3>
<p>Almost every experiment can be conducted using either a between-subjects design or a within-subjects design. This possibility means that researchers must choose between the two approaches based on their relative merits for the particular situation.</p>
<p>Between-subjects experiments have the advantage of being conceptually simpler and requiring less testing time per participant. They also avoid carryover effects without the need for counterbalancing. Within-subjects experiments have the advantage of controlling extraneous participant variables, which generally reduces noise in the data and makes it easier to detect a relationship between the independent and dependent variables.</p>
<p>A good rule of thumb, then, is that if it is possible to conduct a within-subjects experiment (with proper counterbalancing) in the time that is available per participant—and you have no serious concerns about carryover effects—this design is probably the best option. If a within-subjects design would be difficult or impossible to carry out, then you should consider a between-subjects design instead. For example, if you were testing participants in a doctor’s waiting room or shoppers in line at a grocery store, you might not have enough time to test each participant in all conditions and therefore would opt for a between-subjects design. Or imagine you were trying to reduce people’s level of prejudice by having them interact with someone of another race. A within-subjects design with counterbalancing would require testing some participants in the treatment condition first and then in a control condition. But if the treatment works and reduces people’s level of prejudice, then they would no longer be suitable for testing in the control condition. This difficulty is true for many designs that involve a treatment meant to produce long-term change in participants’ behavior (e.g., studies testing the effectiveness of psychotherapy). Clearly, a between-subjects design would be necessary here.</p>
<p>Remember also that using one type of design does not preclude using the other type in a different study. There is no reason that a researcher could not use both a between-subjects design and a within-subjects design to answer the same research question. In fact, professional researchers often take exactly this type of mixed methods approach.</p>
</div>
<div id="section-2" class="section level3">
<h3><span class="header-section-number">7.3.8</span> </h3>
<ul>
<li><p>Experiments can be conducted using either between-subjects or within-subjects designs. Deciding which to use in a particular situation requires careful consideration of the pros and cons of each approach.</p></li>
<li><p>Random assignment to conditions in between-subjects experiments or to orders of conditions in within-subjects experiments is a fundamental element of experimental research. Its purpose is to control extraneous variables so that they do not become confounding variables.</p></li>
<li><p>Experimental research on the effectiveness of a treatment requires both a treatment condition and a control condition, which can be a no-treatment control condition, a placebo control condition, or a wait-list control condition. Experimental treatments can also be compared with the best available alternative.</p></li>
</ul>
</div>
<div id="section-3" class="section level3">
<h3><span class="header-section-number">7.3.9</span> </h3>
<ol style="list-style-type: decimal">
<li><p>Discussion: For each of the following topics, list the pros and cons of a between-subjects and within-subjects design and decide which would be better.</p>
<ul>
<li><p>You want to test the relative effectiveness of two training programs for running a marathon.</p></li>
<li><p>Using photographs of people as stimuli, you want to see if smiling people are perceived as more intelligent than people who are not smiling.</p></li>
<li><p>In a field experiment, you want to see if the way a panhandler is dressed (neatly vs. sloppily) affects whether or not passersby give him any money.</p></li>
<li><p>You want to see if concrete nouns (e.g., dog) are recalled better than abstract nouns (e.g., truth).</p></li>
</ul></li>
<li><p>Discussion: Imagine that an experiment shows that participants who receive psychodynamic therapy for a dog phobia improve more than participants in a no-treatment control group. Explain a fundamental problem with this research design and at least two ways that it might be corrected.</p></li>
</ol>
</div>
</div>
<div id="conducting-experiments" class="section level2">
<h2><span class="header-section-number">7.4</span> Conducting Experiments</h2>
<p>The information presented so far in this chapter is enough to design a basic experiment. When it comes time to conduct that experiment, however, several additional practical issues arise. In this section, we consider some of these issues and how to deal with them. Much of this information applies to nonexperimental studies as well as experimental ones.</p>
<div id="recruiting-participants" class="section level3">
<h3><span class="header-section-number">7.4.1</span> Recruiting Participants</h3>
<p>Of course, at the start of any research project you should be thinking about how you will obtain your participants. Unless you have access to people with schizophrenia or incarcerated juvenile offenders, for example, then there is no point designing a study that focuses on these populations. But even if you plan to use a convenience sample, you will have to recruit participants for your study.</p>
<p>There are several approaches to recruiting participants. One is to use participants from a formal subject pool—an established group of people who have agreed to be contacted about participating in research studies. For example, at many colleges and universities, there is a subject pool consisting of students enrolled in introductory psychology courses who must participate in a certain number of studies to meet a course requirement. Researchers post descriptions of their studies and students sign up to participate, usually via an online system. Participants who are not in subject pools can also be recruited by posting or publishing advertisements or making personal appeals to groups that represent the population of interest. For example, a researcher interested in studying older adults could arrange to speak at a meeting of the residents at a retirement community to explain the study and ask for volunteers.</p>
<p>Even if the participants in a study receive compensation in the form of course credit, a small amount of money, or a chance at being treated for a psychological problem, they are still essentially volunteers. This is worth considering because people who volunteer to participate in psychological research have been shown to differ in predictable ways from those who do not volunteer. Specifically, there is good evidence that on average, volunteers have the following characteristics compared with nonvolunteers (Rosenthal &amp; Rosnow, 1976):</p>
<ul>
<li><p>They are more interested in the topic of the research.</p></li>
<li><p>They are more educated.</p></li>
<li><p>They have a greater need for approval.</p></li>
<li><p>They have higher intelligence quotients (IQs).</p></li>
<li><p>They are more sociable.</p></li>
<li><p>They are higher in social class.</p></li>
</ul>
<p>This difference can be an issue of external validity if there is reason to believe that participants with these characteristics are likely to behave differently than the general population. For example, in testing different methods of persuading people, a rational argument might work better on volunteers than it does on the general population because of their generally higher educational level and IQ.</p>
<p>In many field experiments, the task is not recruiting participants but selecting them. For example, researchers Nicolas Guéguen and Marie-Agnès de Gail conducted a field experiment on the effect of being smiled at on helping, in which the participants were shoppers at a supermarket. A confederate walking down a stairway gazed directly at a shopper walking up the stairway and either smiled or did not smile. Shortly afterward, the shopper encountered another confederate, who dropped some computer diskettes on the ground. The dependent variable was whether or not the shopper stopped to help pick up the diskettes (Guéguen &amp; de Gail, 2003)2. Notice that these participants were not “recruited,” but the researchers still had to select them from among all the shoppers taking the stairs that day. It is extremely important that this kind of selection be done according to a well-defined set of rules that is established before the data collection begins and can be explained clearly afterward. In this case, with each trip down the stairs, the confederate was instructed to gaze at the first person he encountered who appeared to be between the ages of 20 and 50. Only if the person gazed back did he or she become a participant in the study. The point of having a well-defined selection rule is to avoid bias in the selection of participants. For example, if the confederate was free to choose which shoppers he would gaze at, he might choose friendly-looking shoppers when he was set to smile and unfriendly-looking ones when he was not set to smile. As we will see shortly, such biases can be entirely unintentional.</p>
</div>
<div id="standardizing-the-procedure" class="section level3">
<h3><span class="header-section-number">7.4.2</span> Standardizing the Procedure</h3>
<p>It is surprisingly easy to introduce extraneous variables during the procedure. For example, the same experimenter might give clear instructions to one participant but vague instructions to another. Or one experimenter might greet participants warmly while another barely makes eye contact with them. To the extent that such variables affect participants’ behavior, they add noise to the data and make the effect of the independent variable more difficult to detect. If they vary across conditions, they become confounding variables and provide alternative explanations for the results. For example, if participants in a treatment group are tested by a warm and friendly experimenter and participants in a control group are tested by a cold and unfriendly one, then what appears to be an effect of the treatment might actually be an effect of experimenter demeanor. When there are multiple experimenters, the possibility for introducing extraneous variables is even greater, but is often necessary for practical reasons.</p>
<p>It is well known that whether research participants are male or female can affect the results of a study. But what about whether the experimenter is male or female? There is plenty of evidence that this matters too. Male and female experimenters have slightly different ways of interacting with their participants, and of course participants also respond differently to male and female experimenters (Rosenthal, 1976)3. For example, in a recent study on pain perception, participants immersed their hands in icy water for as long as they could (Ibolya, Brake, &amp; Voss, 2004)4. Male participants tolerated the pain longer when the experimenter was a woman, and female participants tolerated it longer when the experimenter was a man.</p>
<p>Researcher Robert Rosenthal has spent much of his career showing that this kind of unintended variation in the procedure does, in fact, affect participants’ behavior. Furthermore, one important source of such variation is the experimenter’s expectations about how participants “should” behave in the experiment. This outcome is referred to as an experimenter expectancy effect (Rosenthal, 1976)5. For example, if an experimenter expects participants in a treatment group to perform better on a task than participants in a control group, then he or she might unintentionally give the treatment group participants clearer instructions or more encouragement or allow them more time to complete the task. In a striking example, Rosenthal and Kermit Fode had several students in a laboratory course in psychology train rats to run through a maze. Although the rats were genetically similar, some of the students were told that they were working with “maze-bright” rats that had been bred to be good learners, and other students were told that they were working with “maze-dull” rats that had been bred to be poor learners. Sure enough, over five days of training, the “maze-bright” rats made more correct responses, made the correct response more quickly, and improved more steadily than the “maze-dull” rats (Rosenthal &amp; Fode, 1963)6. Clearly it had to have been the students’ expectations about how the rats would perform that made the difference. But how? Some clues come from data gathered at the end of the study, which showed that students who expected their rats to learn quickly felt more positively about their animals and reported behaving toward them in a more friendly manner (e.g., handling them more).</p>
<p>The way to minimize unintended variation in the procedure is to standardize it as much as possible so that it is carried out in the same way for all participants regardless of the condition they are in. Here are several ways to do this:</p>
<ul>
<li><p>Create a written protocol that specifies everything that the experimenters are to do and say from the time they greet participants to the time they dismiss them.</p></li>
<li><p>Create standard instructions that participants read themselves or that are read to them word for word by the experimenter.</p></li>
<li><p>Automate the rest of the procedure as much as possible by using software packages for this purpose or even simple computer slide shows.</p></li>
<li><p>Anticipate participants’ questions and either raise and answer them in the instructions or develop standard answers for them.</p></li>
<li><p>Train multiple experimenters on the protocol together and have them practice on each other.</p></li>
<li><p>Be sure that each experimenter tests participants in all conditions.</p></li>
</ul>
<p>Another good practice is to arrange for the experimenters to be “blind” to the research question or to the condition that each participant is tested in. The idea is to minimize experimenter expectancy effects by minimizing the experimenters’ expectations. For example, in a drug study in which each participant receives the drug or a placebo, it is often the case that neither the participants nor the experimenter who interacts with the participants know which condition he or she has been assigned to. Because both the participants and the experimenters are blind to the condition, this technique is referred to as a double-blind study. (A single-blind study is one in which the participant, but not the experimenter, is blind to the condition.) Of course, there are many times this blinding is not possible. For example, if you are both the investigator and the only experimenter, it is not possible for you to remain blind to the research question. Also, in many studies the experimenter must know the condition because he or she must carry out the procedure in a different way in the different conditions.</p>
</div>
<div id="record-keeping" class="section level3">
<h3><span class="header-section-number">7.4.3</span> Record Keeping</h3>
<p>It is essential to keep good records when you conduct an experiment. As discussed earlier, it is typical for experimenters to generate a written sequence of conditions before the study begins and then to test each new participant in the next condition in the sequence. As you test them, it is a good idea to add to this list basic demographic information; the date, time, and place of testing; and the name of the experimenter who did the testing. It is also a good idea to have a place for the experimenter to write down comments about unusual occurrences (e.g., a confused or uncooperative participant) or questions that come up. This kind of information can be useful later if you decide to analyze sex differences or effects of different experimenters, or if a question arises about a particular participant or testing session.</p>
<p>It can also be useful to assign an identification number to each participant as you test them. Simply numbering them consecutively beginning with 1 is usually sufficient. This number can then also be written on any response sheets or questionnaires that participants generate, making it easier to keep them together.</p>
</div>
<div id="pilot-testing" class="section level3">
<h3><span class="header-section-number">7.4.4</span> Pilot Testing</h3>
<p>It is always a good idea to conduct a pilot test of your experiment. A pilot test is a small-scale study conducted to make sure that a new procedure works as planned. In a pilot test, you can recruit participants formally (e.g., from an established participant pool) or you can recruit them informally from among family, friends, classmates, and so on. The number of participants can be small, but it should be enough to give you confidence that your procedure works as planned. There are several important questions that you can answer by conducting a pilot test:</p>
<ul>
<li><p>Do participants understand the instructions?</p></li>
<li><p>What kind of misunderstandings do participants have, what kind of mistakes do they make, and what kind of questions do they ask?</p></li>
<li><p>Do participants become bored or frustrated?</p></li>
<li><p>Is an indirect manipulation effective? (You will need to include a manipulation check.)</p></li>
<li><p>Can participants guess the research question or hypothesis?</p></li>
<li><p>How long does the procedure take?</p></li>
<li><p>Are computer programs or other automated procedures working properly?</p></li>
<li><p>Are data being recorded correctly?</p></li>
</ul>
<p>Of course, to answer some of these questions you will need to observe participants carefully during the procedure and talk with them about it afterward. Participants are often hesitant to criticize a study in front of the researcher, so be sure they understand that their participation is part of a pilot test and you are genuinely interested in feedback that will help you improve the procedure. If the procedure works as planned, then you can proceed with the actual study. If there are problems to be solved, you can solve them, pilot test the new procedure, and continue with this process until you are ready to proceed.</p>
</div>
<div id="section-4" class="section level3">
<h3><span class="header-section-number">7.4.5</span> </h3>
<ul>
<li><p>There are several effective methods you can use to recruit research participants for your experiment, including through formal subject pools, advertisements, and personal appeals. Field experiments require well-defined participant selection procedures.</p></li>
<li><p>It is important to standardize experimental procedures to minimize extraneous variables, including experimenter expectancy effects.</p></li>
<li><p>It is important to conduct one or more small-scale pilot tests of an experiment to be sure that the procedure works as planned.</p></li>
</ul>
</div>
<div id="section-5" class="section level3">
<h3><span class="header-section-number">7.4.6</span> </h3>
<ol style="list-style-type: decimal">
<li><p>Practice: List two ways that you might recruit participants from each of the following populations: a. elderly adults b. unemployed people c. regular exercisers d. math majors</p></li>
<li><p>Discussion: Imagine a study in which you will visually present participants with a list of 20 words, one at a time, wait for a short time, and then ask them to recall as many of the words as they can. In the stressed condition, they are told that they might also be chosen to give a short speech in front of a small audience. In the unstressed condition, they are not told that they might have to give a speech. What are several specific things that you could do to standardize the procedure?</p></li>
</ol>
</div>
</div>
<div id="single-factor-designs-with-2-levels" class="section level2">
<h2><span class="header-section-number">7.5</span> Single Factor Designs with 2 levels</h2>
<p>The simplest kind of experiment has one independent variable (single-factor) with two levels, and one dependent measure of interest. It is important to note that any experiment must have at least 2 levels. If you only measured the dependent variable in one condition, then you would simply be taking a measurement, and not conducting an experiment to see whether the measurement changes between different conditions. In order to find out if the measure changes across conditions, we need at more than one condition.</p>
<p>There are three general ways to manipulate an independent variable between two conditions: 1) present/absent, 2) differing magnitudes, and 3) qualitatively different conditions.</p>
<p>For example, consider a drug company researching a drug to reduce headache pain. They could run a present/absent experiment by having one group of participants receive the drug, and another group receive no drug, and then find out if headache pain was reduced for the group that received the drug. They could also run a magnitude experiment by having one group take one pill and the other group take two (or more) pills. This experiment could test whether taking 2 pills reduces headache pain more than taking 1 pill. Finally, they could run an experiment with qualitatively different conditions. For example, one group could take drug #1 and another group could take a different drug #2. This experiment could test whether one drug is better than another at reducing headache pain.</p>
<div id="the-basic-empirical-question-is-there-a-difference" class="section level3">
<h3><span class="header-section-number">7.5.1</span> The basic empirical question: Is there a difference?</h3>
<p>All experiments have the same basic empirical question: Did the dependent variable change between conditions of the independent variable? There are many other important questions, such as how much change happened, is the change meaningful, and did the independent variable really cause the change or did some other confounding variable cause the change?</p>
<p>At first blush, it is easy to find out if there was any change in the dependent measure. We simply look at the measurement in condition 1 and condition 2. If they are the same, then there was no change. If they are different, then there was a change.</p>
<p>However, in most psychology experiments the measurements in condition 1 and 2 will always be different. This is because most measurements in Psychology are variable. In other words, the measurements themselves change from one person to the next, or within the same person from one time to the next. Imagine measuring something in condition 1 twice. If you were measuring the length of a door twice, you would expect to get the same number twice (no change). However, if you were measuring how fast someone can say a word that begins with “a” twice, you would probably find two different reaction times.</p>
<p>So, there are two kinds of change that researchers have to deal with: real change caused by the independent variable, and random change caused by measuring the dependent variable. Any difference that is found in an experiment could be the result of one or both of these kinds of change. As a result, it is critically important to determine whether an observed change is real, or to due random chance. For example, if an observed difference was due to random change that occurs by chance, then we should not conclude that the independent variable caused the change. If a researcher did not recognize that their observed difference could have been caused by random change, then they might wrongly conclude that it is was their manipulation that caused the change; this kind of inferential error is called a type-I error. The opposite can happen as well. A researcher might find a difference, but conclude that the difference was caused by random change, even though in reality their manipulation caused the change. This kind of inferential error is called a type-II error.</p>
<p>In order to avoid making type I and II inferential errors, researchers need to determine whether the change they observe was real or random. Fortunately, this is a problem that can be solved with inferential statistics. We will go into more detail about how statistics are used to solve this problem. The solution usually does not involve eliminating the influence of random change, although this can be minimized by improving the quality of the measurement (by reducing measurement error and variability). In most cases, there will be always some random change that can not be eliminated. So, researchers are always faced with determining whether there was a real change above and beyond the change that occurs randomly.</p>
<p>The nice thing about random chance, is that it can be estimated very precisely. As a result, for a given experiment, we can determine both how much change can be produced by random chance, and we can determine how often (or how likely) chance alone would produce changes of different sizes. For example, we could show that in some experiment, chance often produces a change of say 10 (units of the measurement), but very rarely (say only 5 % or 1% of the time) produces a change of 20 units. If a researcher found a change of 20 units or greater, then they could be confident that chance did not produce this change, and they would then conclude that the independent variable caused the change. If a researcher found a change of 5 units, then they would recognize that chance alone could have easily produced this change, and they would not be confident that their independent variable caused the change.</p>
</div>
<div id="chance-and-change" class="section level3">
<h3><span class="header-section-number">7.5.2</span> Chance and Change</h3>
<p>In order to understand how to estimate the probability that chance caused a change between conditions, we first need to understand how it is that chance can produce changes in the first place.</p>
<p>Chance can produce changes in a measurement for two simple reasons: measurement variability, and sampling. Measurement variability refers change or instability in a measurement. Sampling refers to the process of taking measurements from a variable.</p>
<p>The easiest way to see how this works is by understanding the concept of sampling from a distribution.</p>
</div>
</div>
<div id="single-factor-designs-with-multiple-levels" class="section level2">
<h2><span class="header-section-number">7.6</span> Single Factor Designs with multiple levels</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simulating-the-null.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-words.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/04-SingleFactor.Rmd",
"text": "Edit"
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
